// Code generated by petri-pilot. DO NOT EDIT.

package order

import (
	"time"
)

// OrderPlaceOrderEvent is emitted when the place_order transition fires.
type OrderPlaceOrderEvent struct {
	AggregateId string    `json:"aggregate_id"`
	Timestamp   time.Time `json:"timestamp"`
}

// EventType returns the event type identifier.
func (e OrderPlaceOrderEvent) EventType() string {
	return "order.place_order"
}

// OrderShipEvent is emitted when the ship transition fires.
type OrderShipEvent struct {
	AggregateId string    `json:"aggregate_id"`
	Timestamp   time.Time `json:"timestamp"`
}

// EventType returns the event type identifier.
func (e OrderShipEvent) EventType() string {
	return "order.ship"
}
