package golang

import (
	"encoding/json"
	"fmt"
	"sort"
	"strings"

	metamodel "github.com/pflow-xyz/go-pflow/metamodel"
)

// This file is the bundle side of code generation: an application whose data
// objects are separate Petri nets composed via a metamodel.Bundle. Each
// subnet ("entity") gets its own Go subpackage with its own State, Aggregate
// and event log — generated by the existing single-net pipeline on that
// subnet's model. What is genuinely new is the app-level material derived
// from FlattenWithMap: the flattened model (the runtime source of truth for
// guards) and the coordinator table for fused transitions (cross-entity
// commands that must append to several entity logs atomically).
//
// Membership questions are answered ONLY via FlattenMap's maps — never by
// parsing flat IDs, which the identity short-circuit (one subnet, no links,
// unprefixed names) would break.

// EntityContext is one subnet's slice of the generated application.
type EntityContext struct {
	SubnetID    string
	PackageName string // Go package / directory name
	Ctx         *Context
}

// CoordinatorMember is one entity's participation in a fused transition.
type CoordinatorMember struct {
	SubnetID        string
	PackageName     string
	LocalTransition string // the transition's name inside its entity
	EventID         string // the event this member appends to its own log
}

// CoordinatorContext is one fused transition: a cross-entity command.
type CoordinatorContext struct {
	FlatID    string // transition ID in the flattened model
	Name      string // Go-safe pascal name
	Initiator string // subnet that owns the HTTP route
	Members   []CoordinatorMember
}

// BundleContext is everything the bundle templates render from.
type BundleContext struct {
	AppName      string
	PackageName  string // root package name
	ModulePath   string
	Entities     []EntityContext
	Coordinators []CoordinatorContext

	// FlatModelJSON is the flattened model, embedded in the generated app —
	// the single runtime source of truth for enablement and guards.
	FlatModelJSON string

	// Warnings carries FlattenMap.Warnings for surfacing in tool output.
	Warnings []string
}

// entityPackageName makes a subnet ID into a Go package name.
func entityPackageName(subnetID string) string {
	name := Ident(strings.ToLower(Snake(subnetID)))
	if name == "" {
		name = "entity"
	}
	return name
}

// Ident strips non-identifier characters. Exposed for bundle naming.
func Ident(s string) string {
	var b strings.Builder
	for _, r := range s {
		if r == '_' || r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z' || r >= '0' && r <= '9' {
			b.WriteRune(r)
		}
	}
	return b.String()
}

// Snake converts CamelCase / kebab-case / spaces to snake_case.
func Snake(s string) string {
	var b strings.Builder
	prevLower := false
	for _, r := range s {
		switch {
		case r >= 'A' && r <= 'Z':
			if prevLower {
				b.WriteByte('_')
			}
			b.WriteRune(r + ('a' - 'A'))
			prevLower = false
		case r == ' ' || r == '-':
			b.WriteByte('_')
			prevLower = false
		default:
			b.WriteRune(r)
			prevLower = r >= 'a' && r <= 'z' || r >= '0' && r <= '9'
		}
	}
	return b.String()
}

// memberRef splits a FlattenMap group member ("<subnet>/<transition>") into
// its parts. This is the documented wire format of FusedGroups/Wires values,
// not flat-ID guessing; subnet IDs cannot contain "/" (bundle validation
// namespaces with it).
func memberRef(member string) (subnet, local string, err error) {
	i := strings.Index(member, "/")
	if i < 0 {
		return "", "", fmt.Errorf("malformed fused-group member %q", member)
	}
	return member[:i], member[i+1:], nil
}

// NewBundleContext validates and flattens the bundle, builds one entity
// context per subnet from that subnet's own model, and derives the
// coordinator table for fused transitions from the FlattenMap.
func NewBundleContext(b *metamodel.Bundle, opts ContextOptions) (*BundleContext, error) {
	flat, fm, err := b.FlattenWithMap()
	if err != nil {
		return nil, fmt.Errorf("flattening bundle: %w", err)
	}

	flatJSON, err := json.Marshal(flat)
	if err != nil {
		return nil, fmt.Errorf("embedding flat model: %w", err)
	}

	bc := &BundleContext{
		AppName:       b.Name,
		PackageName:   entityPackageName(b.Name),
		ModulePath:    opts.ModulePath,
		FlatModelJSON: string(flatJSON),
	}
	for _, w := range fm.Warnings {
		bc.Warnings = append(bc.Warnings, w.Message)
	}

	// Entities, sorted by subnet ID for deterministic output.
	subnets := append([]metamodel.Subnet(nil), b.Subnets...)
	sort.Slice(subnets, func(i, j int) bool { return subnets[i].ID < subnets[j].ID })
	pkgBySubnet := map[string]string{}
	seenPkg := map[string]bool{}
	for _, sn := range subnets {
		pkg := entityPackageName(sn.ID)
		if seenPkg[pkg] {
			return nil, fmt.Errorf("subnets %q and another map to the same package name %q", sn.ID, pkg)
		}
		seenPkg[pkg] = true
		pkgBySubnet[sn.ID] = pkg

		ctx, err := NewContext(sn.Model, ContextOptions{
			ModulePath:  opts.ModulePath,
			PackageName: pkg,
		})
		if err != nil {
			return nil, fmt.Errorf("entity %q: %w", sn.ID, err)
		}
		bc.Entities = append(bc.Entities, EntityContext{
			SubnetID:    sn.ID,
			PackageName: pkg,
			Ctx:         ctx,
		})
	}

	// Transitions with an incoming EventLink can never be a coordinator's
	// initiator — mirrors upstream's initiator rule (compose_fuse.go).
	hasIncoming := map[string]bool{}
	for _, l := range b.Links {
		if l.Kind == metamodel.EventLink {
			hasIncoming[l.To.Subnet+"/"+l.To.Transition] = true
		}
	}

	// Per-subnet transition -> event lookup, mirroring upstream's
	// componentEvent fallback chain (Event, then ID).
	eventOf := func(subnet, transition string) string {
		for _, sn := range b.Subnets {
			if sn.ID != subnet {
				continue
			}
			for _, t := range sn.Model.Transitions {
				if t.ID == transition {
					if t.Event != "" {
						return t.Event
					}
					return t.ID
				}
			}
		}
		return transition
	}

	flatIDs := make([]string, 0, len(fm.FusedGroups))
	for flatID := range fm.FusedGroups {
		flatIDs = append(flatIDs, flatID)
	}
	sort.Strings(flatIDs)
	for _, flatID := range flatIDs {
		members := append([]string(nil), fm.FusedGroups[flatID]...)
		sort.Strings(members)

		coord := CoordinatorContext{
			FlatID: flatID,
			Name:   ToPascalCase(Ident(Snake(flatID))),
		}
		for _, m := range members {
			subnet, local, err := memberRef(m)
			if err != nil {
				return nil, err
			}
			coord.Members = append(coord.Members, CoordinatorMember{
				SubnetID:        subnet,
				PackageName:     pkgBySubnet[subnet],
				LocalTransition: local,
				EventID:         eventOf(subnet, local),
			})
			if coord.Initiator == "" && !hasIncoming[m] {
				coord.Initiator = subnet
			}
		}
		if coord.Initiator == "" {
			// Link cycle: every member has an incoming link. Upstream
			// resolves to the smallest member; members is sorted.
			coord.Initiator, _, _ = memberRef(members[0])
		}
		bc.Coordinators = append(bc.Coordinators, coord)
	}

	return bc, nil
}
