load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "api",
    srcs = [
        "handler.go",
        "router.go",
    ],
    importpath = "github.com/pflow-xyz/petri-pilot/pkg/runtime/api",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_pflow_xyz_go_pflow//eventsource",
        "@com_github_pflow_xyz_go_pflow//metamodel",
    ],
)
