load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "bundle",
    srcs = [
        "compile.go",
        "doc.go",
    ],
    importpath = "github.com/pflow-xyz/petri-pilot/pkg/bundle",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/extensions",
        "@com_github_pflow_xyz_go_pflow//metamodel",
    ],
)

go_test(
    name = "bundle_test",
    srcs = ["compile_test.go"],
    embed = [":bundle"],
    deps = [
        "//pkg/extensions",
        "@com_github_pflow_xyz_go_pflow//metamodel",
    ],
)
