// Code generated by petri-pilot. DO NOT EDIT.

package diningphilosophers

import (
	"context"
	"encoding/json"
	"net/http"

	"github.com/pflow-xyz/go-pflow/eventsource"
	"github.com/pflow-xyz/petri-pilot/examples/diningphilosophers/graph"
	"github.com/pflow-xyz/petri-pilot/pkg/serve"
)

// GraphQLConfig holds the GraphQL server configuration.
var GraphQLConfig = struct {
	Path       string
	Playground bool
}{
	Path:       "/graphql",
	Playground: true,
}

// GraphQLHandler creates the GraphQL HTTP handler.
func GraphQLHandler(app *Application) http.HandlerFunc {
	resolver := graph.NewResolver(&graphQLApp{app: app})
	h := &graphQLHandler{resolver: resolver}
	return h.ServeHTTP
}

// PlaygroundHandler serves the GraphQL Playground UI.
func PlaygroundHandler() http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "text/html; charset=utf-8")
		w.Write([]byte(playgroundHTML))
	}
}

var playgroundHTML = "<!DOCTYPE html>\n" +
	"<html>\n" +
	"<head>\n" +
	"  <title>dining-philosophers GraphQL Playground</title>\n" +
	"  <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/graphql-playground-react/build/static/css/index.css\" />\n" +
	"  <link rel=\"shortcut icon\" href=\"https://cdn.jsdelivr.net/npm/graphql-playground-react/build/favicon.png\" />\n" +
	"  <script src=\"https://cdn.jsdelivr.net/npm/graphql-playground-react/build/static/js/middleware.js\"></script>\n" +
	"</head>\n" +
	"<body>\n" +
	"  <div id=\"root\"></div>\n" +
	"  <script>\n" +
	"    window.addEventListener('load', function() {\n" +
	"      GraphQLPlayground.init(document.getElementById('root'), {\n" +
	"        endpoint: '/graphql',\n" +
	"        settings: {\n" +
	"          'editor.theme': 'dark',\n" +
	"          'editor.fontFamily': \"'Source Code Pro', 'Consolas', 'Inconsolata', 'Droid Sans Mono', 'Monaco', monospace\",\n" +
	"          'editor.fontSize': 14,\n" +
	"          'request.credentials': 'same-origin'\n" +
	"        }\n" +
	"      })\n" +
	"    })\n" +
	"  </script>\n" +
	"</body>\n" +
	"</html>\n"

// graphQLApp wraps Application to implement the resolver interface.
type graphQLApp struct {
	app *Application
}

func (a *graphQLApp) Create(ctx context.Context) (string, error) {
	return a.app.Create(ctx)
}

func (a *graphQLApp) Load(ctx context.Context, id string) (graph.Aggregate, error) {
	return a.app.Load(ctx, id)
}

func (a *graphQLApp) GetState(ctx context.Context, id string) (graph.Aggregate, error) {
	return a.app.GetState(ctx, id)
}

func (a *graphQLApp) Execute(ctx context.Context, id, transition string, data map[string]any) (graph.Aggregate, error) {
	return a.app.Execute(ctx, id, transition, data)
}

func (a *graphQLApp) HealthCheck(ctx context.Context) error {
	return a.app.HealthCheck(ctx)
}

func (a *graphQLApp) GetStore() eventsource.Store {
	return a.app.store
}

// graphQLHandler implements a simple GraphQL HTTP handler.
type graphQLHandler struct {
	resolver *graph.Resolver
}

func (h *graphQLHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return
	}

	var req struct {
		Query         string                 `json:"query"`
		OperationName string                 `json:"operationName"`
		Variables     map[string]interface{} `json:"variables"`
	}

	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	// Execute the GraphQL operation
	result := h.executeGraphQL(r.Context(), req.Query, req.OperationName, req.Variables)

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(result)
}

func (h *graphQLHandler) executeGraphQL(ctx context.Context, query, operationName string, variables map[string]interface{}) map[string]interface{} {
	// This is a simplified GraphQL executor
	// In production, use github.com/99designs/gqlgen for full spec compliance

	result := make(map[string]interface{})
	data := make(map[string]interface{})
	var errors []map[string]interface{}

	// Detect mutation vs query
	isMutation := containsString(query, "mutation")

	// Handle create mutation (supports both "createPackageName" and "package_create" naming)
	// Use matchField to avoid substring collision (e.g. "blogpost_create" vs "blogpost_create_post")
	if isMutation && (matchField(query, "createDiningphilosophers") || matchField(query, "diningphilosophers_create")) {
		state, err := h.resolver.CreateDiningphilosophers(ctx)
		if err != nil {
			errors = append(errors, map[string]interface{}{"message": err.Error()})
		} else {
			// Return under whichever key the query used
			if matchField(query, "diningphilosophers_create") {
				data["diningphilosophers_create"] = state
			} else {
				data["createDiningphilosophers"] = state
			}
		}
	}

	// Handle transition mutations (supports both "transitionName" and "package_transition" naming)

	if isMutation && (containsString(query, "diningphilosophers_pickup_left_0") || containsString(query, "pickupLeft0")) {
		input := graph.PickupLeft0Input{}
		if vars, ok := variables["input"].(map[string]interface{}); ok {
			if id, ok := vars["aggregateId"].(string); ok {
				input.AggregateID = id
			}
		}
		res, err := h.resolver.PickupLeft0(ctx, input)
		if err != nil {
			errors = append(errors, map[string]interface{}{"message": err.Error()})
		} else {
			// Return under whichever key the query used
			if containsString(query, "diningphilosophers_pickup_left_0") {
				data["diningphilosophers_pickup_left_0"] = res
			} else {
				data["pickupLeft0"] = res
			}
		}
	}

	if isMutation && (containsString(query, "diningphilosophers_pickup_left_1") || containsString(query, "pickupLeft1")) {
		input := graph.PickupLeft1Input{}
		if vars, ok := variables["input"].(map[string]interface{}); ok {
			if id, ok := vars["aggregateId"].(string); ok {
				input.AggregateID = id
			}
		}
		res, err := h.resolver.PickupLeft1(ctx, input)
		if err != nil {
			errors = append(errors, map[string]interface{}{"message": err.Error()})
		} else {
			// Return under whichever key the query used
			if containsString(query, "diningphilosophers_pickup_left_1") {
				data["diningphilosophers_pickup_left_1"] = res
			} else {
				data["pickupLeft1"] = res
			}
		}
	}

	if isMutation && (containsString(query, "diningphilosophers_pickup_left_2") || containsString(query, "pickupLeft2")) {
		input := graph.PickupLeft2Input{}
		if vars, ok := variables["input"].(map[string]interface{}); ok {
			if id, ok := vars["aggregateId"].(string); ok {
				input.AggregateID = id
			}
		}
		res, err := h.resolver.PickupLeft2(ctx, input)
		if err != nil {
			errors = append(errors, map[string]interface{}{"message": err.Error()})
		} else {
			// Return under whichever key the query used
			if containsString(query, "diningphilosophers_pickup_left_2") {
				data["diningphilosophers_pickup_left_2"] = res
			} else {
				data["pickupLeft2"] = res
			}
		}
	}

	if isMutation && (containsString(query, "diningphilosophers_pickup_left_3") || containsString(query, "pickupLeft3")) {
		input := graph.PickupLeft3Input{}
		if vars, ok := variables["input"].(map[string]interface{}); ok {
			if id, ok := vars["aggregateId"].(string); ok {
				input.AggregateID = id
			}
		}
		res, err := h.resolver.PickupLeft3(ctx, input)
		if err != nil {
			errors = append(errors, map[string]interface{}{"message": err.Error()})
		} else {
			// Return under whichever key the query used
			if containsString(query, "diningphilosophers_pickup_left_3") {
				data["diningphilosophers_pickup_left_3"] = res
			} else {
				data["pickupLeft3"] = res
			}
		}
	}

	if isMutation && (containsString(query, "diningphilosophers_pickup_left_4") || containsString(query, "pickupLeft4")) {
		input := graph.PickupLeft4Input{}
		if vars, ok := variables["input"].(map[string]interface{}); ok {
			if id, ok := vars["aggregateId"].(string); ok {
				input.AggregateID = id
			}
		}
		res, err := h.resolver.PickupLeft4(ctx, input)
		if err != nil {
			errors = append(errors, map[string]interface{}{"message": err.Error()})
		} else {
			// Return under whichever key the query used
			if containsString(query, "diningphilosophers_pickup_left_4") {
				data["diningphilosophers_pickup_left_4"] = res
			} else {
				data["pickupLeft4"] = res
			}
		}
	}

	if isMutation && (containsString(query, "diningphilosophers_pickup_right_0") || containsString(query, "pickupRight0")) {
		input := graph.PickupRight0Input{}
		if vars, ok := variables["input"].(map[string]interface{}); ok {
			if id, ok := vars["aggregateId"].(string); ok {
				input.AggregateID = id
			}
		}
		res, err := h.resolver.PickupRight0(ctx, input)
		if err != nil {
			errors = append(errors, map[string]interface{}{"message": err.Error()})
		} else {
			// Return under whichever key the query used
			if containsString(query, "diningphilosophers_pickup_right_0") {
				data["diningphilosophers_pickup_right_0"] = res
			} else {
				data["pickupRight0"] = res
			}
		}
	}

	if isMutation && (containsString(query, "diningphilosophers_pickup_right_1") || containsString(query, "pickupRight1")) {
		input := graph.PickupRight1Input{}
		if vars, ok := variables["input"].(map[string]interface{}); ok {
			if id, ok := vars["aggregateId"].(string); ok {
				input.AggregateID = id
			}
		}
		res, err := h.resolver.PickupRight1(ctx, input)
		if err != nil {
			errors = append(errors, map[string]interface{}{"message": err.Error()})
		} else {
			// Return under whichever key the query used
			if containsString(query, "diningphilosophers_pickup_right_1") {
				data["diningphilosophers_pickup_right_1"] = res
			} else {
				data["pickupRight1"] = res
			}
		}
	}

	if isMutation && (containsString(query, "diningphilosophers_pickup_right_2") || containsString(query, "pickupRight2")) {
		input := graph.PickupRight2Input{}
		if vars, ok := variables["input"].(map[string]interface{}); ok {
			if id, ok := vars["aggregateId"].(string); ok {
				input.AggregateID = id
			}
		}
		res, err := h.resolver.PickupRight2(ctx, input)
		if err != nil {
			errors = append(errors, map[string]interface{}{"message": err.Error()})
		} else {
			// Return under whichever key the query used
			if containsString(query, "diningphilosophers_pickup_right_2") {
				data["diningphilosophers_pickup_right_2"] = res
			} else {
				data["pickupRight2"] = res
			}
		}
	}

	if isMutation && (containsString(query, "diningphilosophers_pickup_right_3") || containsString(query, "pickupRight3")) {
		input := graph.PickupRight3Input{}
		if vars, ok := variables["input"].(map[string]interface{}); ok {
			if id, ok := vars["aggregateId"].(string); ok {
				input.AggregateID = id
			}
		}
		res, err := h.resolver.PickupRight3(ctx, input)
		if err != nil {
			errors = append(errors, map[string]interface{}{"message": err.Error()})
		} else {
			// Return under whichever key the query used
			if containsString(query, "diningphilosophers_pickup_right_3") {
				data["diningphilosophers_pickup_right_3"] = res
			} else {
				data["pickupRight3"] = res
			}
		}
	}

	if isMutation && (containsString(query, "diningphilosophers_pickup_right_4") || containsString(query, "pickupRight4")) {
		input := graph.PickupRight4Input{}
		if vars, ok := variables["input"].(map[string]interface{}); ok {
			if id, ok := vars["aggregateId"].(string); ok {
				input.AggregateID = id
			}
		}
		res, err := h.resolver.PickupRight4(ctx, input)
		if err != nil {
			errors = append(errors, map[string]interface{}{"message": err.Error()})
		} else {
			// Return under whichever key the query used
			if containsString(query, "diningphilosophers_pickup_right_4") {
				data["diningphilosophers_pickup_right_4"] = res
			} else {
				data["pickupRight4"] = res
			}
		}
	}

	if isMutation && (containsString(query, "diningphilosophers_release_0") || containsString(query, "release0")) {
		input := graph.Release0Input{}
		if vars, ok := variables["input"].(map[string]interface{}); ok {
			if id, ok := vars["aggregateId"].(string); ok {
				input.AggregateID = id
			}
		}
		res, err := h.resolver.Release0(ctx, input)
		if err != nil {
			errors = append(errors, map[string]interface{}{"message": err.Error()})
		} else {
			// Return under whichever key the query used
			if containsString(query, "diningphilosophers_release_0") {
				data["diningphilosophers_release_0"] = res
			} else {
				data["release0"] = res
			}
		}
	}

	if isMutation && (containsString(query, "diningphilosophers_release_1") || containsString(query, "release1")) {
		input := graph.Release1Input{}
		if vars, ok := variables["input"].(map[string]interface{}); ok {
			if id, ok := vars["aggregateId"].(string); ok {
				input.AggregateID = id
			}
		}
		res, err := h.resolver.Release1(ctx, input)
		if err != nil {
			errors = append(errors, map[string]interface{}{"message": err.Error()})
		} else {
			// Return under whichever key the query used
			if containsString(query, "diningphilosophers_release_1") {
				data["diningphilosophers_release_1"] = res
			} else {
				data["release1"] = res
			}
		}
	}

	if isMutation && (containsString(query, "diningphilosophers_release_2") || containsString(query, "release2")) {
		input := graph.Release2Input{}
		if vars, ok := variables["input"].(map[string]interface{}); ok {
			if id, ok := vars["aggregateId"].(string); ok {
				input.AggregateID = id
			}
		}
		res, err := h.resolver.Release2(ctx, input)
		if err != nil {
			errors = append(errors, map[string]interface{}{"message": err.Error()})
		} else {
			// Return under whichever key the query used
			if containsString(query, "diningphilosophers_release_2") {
				data["diningphilosophers_release_2"] = res
			} else {
				data["release2"] = res
			}
		}
	}

	if isMutation && (containsString(query, "diningphilosophers_release_3") || containsString(query, "release3")) {
		input := graph.Release3Input{}
		if vars, ok := variables["input"].(map[string]interface{}); ok {
			if id, ok := vars["aggregateId"].(string); ok {
				input.AggregateID = id
			}
		}
		res, err := h.resolver.Release3(ctx, input)
		if err != nil {
			errors = append(errors, map[string]interface{}{"message": err.Error()})
		} else {
			// Return under whichever key the query used
			if containsString(query, "diningphilosophers_release_3") {
				data["diningphilosophers_release_3"] = res
			} else {
				data["release3"] = res
			}
		}
	}

	if isMutation && (containsString(query, "diningphilosophers_release_4") || containsString(query, "release4")) {
		input := graph.Release4Input{}
		if vars, ok := variables["input"].(map[string]interface{}); ok {
			if id, ok := vars["aggregateId"].(string); ok {
				input.AggregateID = id
			}
		}
		res, err := h.resolver.Release4(ctx, input)
		if err != nil {
			errors = append(errors, map[string]interface{}{"message": err.Error()})
		} else {
			// Return under whichever key the query used
			if containsString(query, "diningphilosophers_release_4") {
				data["diningphilosophers_release_4"] = res
			} else {
				data["release4"] = res
			}
		}
	}

	// Handle query for single aggregate
	if !isMutation && containsString(query, "diningphilosophers(") {
		id := ""
		if idVar, ok := variables["id"].(string); ok {
			id = idVar
		}
		if id != "" {
			state, err := h.resolver.DiningPhilosophers(ctx, id)
			if err != nil {
				errors = append(errors, map[string]interface{}{"message": err.Error()})
			} else {
				data["diningphilosophers"] = state
			}
		}
	}

	// Handle list query
	if !isMutation && containsString(query, "diningphilosophersList") {
		var place *string
		var page, perPage *int
		if p, ok := variables["place"].(string); ok {
			place = &p
		}
		if p, ok := variables["page"].(float64); ok {
			pi := int(p)
			page = &pi
		}
		if p, ok := variables["perPage"].(float64); ok {
			pi := int(p)
			perPage = &pi
		}
		list, err := h.resolver.DiningPhilosophersList(ctx, place, page, perPage)
		if err != nil {
			errors = append(errors, map[string]interface{}{"message": err.Error()})
		} else {
			data["diningphilosophersList"] = list
		}
	}

	// Handle events query
	if !isMutation && containsString(query, "events(") {
		aggID := ""
		var from *int
		if id, ok := variables["aggregateId"].(string); ok {
			aggID = id
		}
		if f, ok := variables["from"].(float64); ok {
			fi := int(f)
			from = &fi
		}
		if aggID != "" {
			events, err := h.resolver.Events(ctx, aggID, from)
			if err != nil {
				errors = append(errors, map[string]interface{}{"message": err.Error()})
			} else {
				data["events"] = events
			}
		}
	}

	result["data"] = data
	if len(errors) > 0 {
		result["errors"] = errors
	}

	return result
}

func containsString(s, substr string) bool {
	return len(s) >= len(substr) && (s == substr || len(s) > 0 && containsStringHelper(s, substr))
}

func containsStringHelper(s, substr string) bool {
	for i := 0; i <= len(s)-len(substr); i++ {
		if s[i:i+len(substr)] == substr {
			return true
		}
	}
	return false
}

// matchField checks if a GraphQL field name appears in a query as a complete identifier.
// Unlike containsString, it ensures the match is not a prefix of a longer identifier.
// e.g. matchField("blogpost_create_post(...)", "blogpost_create") returns false.
func matchField(s, field string) bool {
	for i := 0; i <= len(s)-len(field); i++ {
		if s[i:i+len(field)] == field {
			// Check that the next character is not an identifier char
			if i+len(field) >= len(s) {
				return true
			}
			next := s[i+len(field)]
			if !isIdentChar(next) {
				return true
			}
		}
	}
	return false
}

func isIdentChar(c byte) bool {
	return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '_'
}

// GraphQLSchemaString is the GraphQL schema for this service.
// Used by the unified GraphQL endpoint to combine schemas.
var GraphQLSchemaString = `# GraphQL schema for dining-philosophers

scalar Time

type Query {
  # Get aggregate state by ID
  diningphilosophers(id: ID!): AggregateState

  # List aggregates with optional filtering
  diningphilosophersList(place: String, page: Int, perPage: Int): AggregateList!

  # Event history for an aggregate
  events(aggregateId: ID!, from: Int): [Event!]!

  # Get state at specific version
  stateAtVersion(aggregateId: ID!, version: Int!): AggregateState
}

type Mutation {
  # Create a new diningphilosophers instance
  createDiningphilosophers: AggregateState!

  # Philosopher 0 picks up left fork (fork 4)
  pickupLeft0(input: PickupLeft0Input!): TransitionResult!

  # Philosopher 1 picks up left fork (fork 0)
  pickupLeft1(input: PickupLeft1Input!): TransitionResult!

  # Philosopher 2 picks up left fork (fork 1)
  pickupLeft2(input: PickupLeft2Input!): TransitionResult!

  # Philosopher 3 picks up left fork (fork 2)
  pickupLeft3(input: PickupLeft3Input!): TransitionResult!

  # Philosopher 4 picks up left fork (fork 3)
  pickupLeft4(input: PickupLeft4Input!): TransitionResult!

  # Philosopher 0 picks up right fork (fork 0)
  pickupRight0(input: PickupRight0Input!): TransitionResult!

  # Philosopher 1 picks up right fork (fork 1)
  pickupRight1(input: PickupRight1Input!): TransitionResult!

  # Philosopher 2 picks up right fork (fork 2)
  pickupRight2(input: PickupRight2Input!): TransitionResult!

  # Philosopher 3 picks up right fork (fork 3)
  pickupRight3(input: PickupRight3Input!): TransitionResult!

  # Philosopher 4 picks up right fork (fork 4)
  pickupRight4(input: PickupRight4Input!): TransitionResult!

  # Philosopher 0 releases both forks and goes back to thinking
  release0(input: Release0Input!): TransitionResult!

  # Philosopher 1 releases both forks and goes back to thinking
  release1(input: Release1Input!): TransitionResult!

  # Philosopher 2 releases both forks and goes back to thinking
  release2(input: Release2Input!): TransitionResult!

  # Philosopher 3 releases both forks and goes back to thinking
  release3(input: Release3Input!): TransitionResult!

  # Philosopher 4 releases both forks and goes back to thinking
  release4(input: Release4Input!): TransitionResult!
}

# Aggregate state representation
type AggregateState {
  id: ID!
  version: Int!
  state: State!
  places: Places!
  enabledTransitions: [String!]!
}

# Workflow state with all places
type State {
  thinking0: Int!
  thinking1: Int!
  thinking2: Int!
  thinking3: Int!
  thinking4: Int!
  fork0: Int!
  fork1: Int!
  fork2: Int!
  fork3: Int!
  fork4: Int!
  hasLeft0: Int!
  hasLeft1: Int!
  hasLeft2: Int!
  hasLeft3: Int!
  hasLeft4: Int!
  eating0: Int!
  eating1: Int!
  eating2: Int!
  eating3: Int!
  eating4: Int!
}

# Token counts for each place
type Places {
  thinking0: Int!
  thinking1: Int!
  thinking2: Int!
  thinking3: Int!
  thinking4: Int!
  fork0: Int!
  fork1: Int!
  fork2: Int!
  fork3: Int!
  fork4: Int!
  hasLeft0: Int!
  hasLeft1: Int!
  hasLeft2: Int!
  hasLeft3: Int!
  hasLeft4: Int!
  eating0: Int!
  eating1: Int!
  eating2: Int!
  eating3: Int!
  eating4: Int!
}

# Result of a transition execution
type TransitionResult {
  success: Boolean!
  aggregateId: ID
  version: Int
  state: Places
  enabledTransitions: [String!]
  error: String
}

# Paginated list of aggregates
type AggregateList {
  items: [AggregateState!]!
  total: Int!
  page: Int!
  perPage: Int!
}


# Event record
type Event {
  id: ID!
  streamId: String!
  type: String!
  version: Int!
  timestamp: Time!
  data: String!
}


# Input types for mutations

input PickupLeft0Input {
  aggregateId: ID!
}


input PickupLeft1Input {
  aggregateId: ID!
}


input PickupLeft2Input {
  aggregateId: ID!
}


input PickupLeft3Input {
  aggregateId: ID!
}


input PickupLeft4Input {
  aggregateId: ID!
}


input PickupRight0Input {
  aggregateId: ID!
}


input PickupRight1Input {
  aggregateId: ID!
}


input PickupRight2Input {
  aggregateId: ID!
}


input PickupRight3Input {
  aggregateId: ID!
}


input PickupRight4Input {
  aggregateId: ID!
}


input Release0Input {
  aggregateId: ID!
}


input Release1Input {
  aggregateId: ID!
}


input Release2Input {
  aggregateId: ID!
}


input Release3Input {
  aggregateId: ID!
}


input Release4Input {
  aggregateId: ID!
}

`

// GraphQLResolversMap returns a map of resolver functions for the unified GraphQL endpoint.
func GraphQLResolversMap(app *Application) map[string]serve.GraphQLResolver {
	gqlApp := &graphQLApp{app: app}
	resolver := graph.NewResolver(gqlApp)

	resolvers := make(map[string]serve.GraphQLResolver)

	// Query resolvers
	resolvers["diningphilosophers"] = func(ctx context.Context, variables map[string]any) (any, error) {
		id, _ := variables["id"].(string)
		return resolver.DiningPhilosophers(ctx, id)
	}

	resolvers["diningphilosophersList"] = func(ctx context.Context, variables map[string]any) (any, error) {
		var place *string
		var page, perPage *int
		if p, ok := variables["place"].(string); ok {
			place = &p
		}
		if p, ok := variables["page"].(float64); ok {
			pi := int(p)
			page = &pi
		}
		if p, ok := variables["perPage"].(float64); ok {
			pi := int(p)
			perPage = &pi
		}
		return resolver.DiningPhilosophersList(ctx, place, page, perPage)
	}

	// Mutation resolvers (register both underscore and camelCase names for compatibility)
	resolvers["diningphilosophers_create"] = func(ctx context.Context, _ map[string]any) (any, error) {
		return resolver.CreateDiningphilosophers(ctx)
	}
	resolvers["createDiningphilosophers"] = resolvers["diningphilosophers_create"]

	resolvers["diningphilosophers_pickup_left_0"] = func(ctx context.Context, variables map[string]any) (any, error) {
		input := graph.PickupLeft0Input{}
		if vars, ok := variables["input"].(map[string]any); ok {
			if id, ok := vars["aggregateId"].(string); ok {
				input.AggregateID = id
			}
		}
		return resolver.PickupLeft0(ctx, input)
	}
	resolvers["pickupLeft0"] = resolvers["diningphilosophers_pickup_left_0"]

	resolvers["diningphilosophers_pickup_left_1"] = func(ctx context.Context, variables map[string]any) (any, error) {
		input := graph.PickupLeft1Input{}
		if vars, ok := variables["input"].(map[string]any); ok {
			if id, ok := vars["aggregateId"].(string); ok {
				input.AggregateID = id
			}
		}
		return resolver.PickupLeft1(ctx, input)
	}
	resolvers["pickupLeft1"] = resolvers["diningphilosophers_pickup_left_1"]

	resolvers["diningphilosophers_pickup_left_2"] = func(ctx context.Context, variables map[string]any) (any, error) {
		input := graph.PickupLeft2Input{}
		if vars, ok := variables["input"].(map[string]any); ok {
			if id, ok := vars["aggregateId"].(string); ok {
				input.AggregateID = id
			}
		}
		return resolver.PickupLeft2(ctx, input)
	}
	resolvers["pickupLeft2"] = resolvers["diningphilosophers_pickup_left_2"]

	resolvers["diningphilosophers_pickup_left_3"] = func(ctx context.Context, variables map[string]any) (any, error) {
		input := graph.PickupLeft3Input{}
		if vars, ok := variables["input"].(map[string]any); ok {
			if id, ok := vars["aggregateId"].(string); ok {
				input.AggregateID = id
			}
		}
		return resolver.PickupLeft3(ctx, input)
	}
	resolvers["pickupLeft3"] = resolvers["diningphilosophers_pickup_left_3"]

	resolvers["diningphilosophers_pickup_left_4"] = func(ctx context.Context, variables map[string]any) (any, error) {
		input := graph.PickupLeft4Input{}
		if vars, ok := variables["input"].(map[string]any); ok {
			if id, ok := vars["aggregateId"].(string); ok {
				input.AggregateID = id
			}
		}
		return resolver.PickupLeft4(ctx, input)
	}
	resolvers["pickupLeft4"] = resolvers["diningphilosophers_pickup_left_4"]

	resolvers["diningphilosophers_pickup_right_0"] = func(ctx context.Context, variables map[string]any) (any, error) {
		input := graph.PickupRight0Input{}
		if vars, ok := variables["input"].(map[string]any); ok {
			if id, ok := vars["aggregateId"].(string); ok {
				input.AggregateID = id
			}
		}
		return resolver.PickupRight0(ctx, input)
	}
	resolvers["pickupRight0"] = resolvers["diningphilosophers_pickup_right_0"]

	resolvers["diningphilosophers_pickup_right_1"] = func(ctx context.Context, variables map[string]any) (any, error) {
		input := graph.PickupRight1Input{}
		if vars, ok := variables["input"].(map[string]any); ok {
			if id, ok := vars["aggregateId"].(string); ok {
				input.AggregateID = id
			}
		}
		return resolver.PickupRight1(ctx, input)
	}
	resolvers["pickupRight1"] = resolvers["diningphilosophers_pickup_right_1"]

	resolvers["diningphilosophers_pickup_right_2"] = func(ctx context.Context, variables map[string]any) (any, error) {
		input := graph.PickupRight2Input{}
		if vars, ok := variables["input"].(map[string]any); ok {
			if id, ok := vars["aggregateId"].(string); ok {
				input.AggregateID = id
			}
		}
		return resolver.PickupRight2(ctx, input)
	}
	resolvers["pickupRight2"] = resolvers["diningphilosophers_pickup_right_2"]

	resolvers["diningphilosophers_pickup_right_3"] = func(ctx context.Context, variables map[string]any) (any, error) {
		input := graph.PickupRight3Input{}
		if vars, ok := variables["input"].(map[string]any); ok {
			if id, ok := vars["aggregateId"].(string); ok {
				input.AggregateID = id
			}
		}
		return resolver.PickupRight3(ctx, input)
	}
	resolvers["pickupRight3"] = resolvers["diningphilosophers_pickup_right_3"]

	resolvers["diningphilosophers_pickup_right_4"] = func(ctx context.Context, variables map[string]any) (any, error) {
		input := graph.PickupRight4Input{}
		if vars, ok := variables["input"].(map[string]any); ok {
			if id, ok := vars["aggregateId"].(string); ok {
				input.AggregateID = id
			}
		}
		return resolver.PickupRight4(ctx, input)
	}
	resolvers["pickupRight4"] = resolvers["diningphilosophers_pickup_right_4"]

	resolvers["diningphilosophers_release_0"] = func(ctx context.Context, variables map[string]any) (any, error) {
		input := graph.Release0Input{}
		if vars, ok := variables["input"].(map[string]any); ok {
			if id, ok := vars["aggregateId"].(string); ok {
				input.AggregateID = id
			}
		}
		return resolver.Release0(ctx, input)
	}
	resolvers["release0"] = resolvers["diningphilosophers_release_0"]

	resolvers["diningphilosophers_release_1"] = func(ctx context.Context, variables map[string]any) (any, error) {
		input := graph.Release1Input{}
		if vars, ok := variables["input"].(map[string]any); ok {
			if id, ok := vars["aggregateId"].(string); ok {
				input.AggregateID = id
			}
		}
		return resolver.Release1(ctx, input)
	}
	resolvers["release1"] = resolvers["diningphilosophers_release_1"]

	resolvers["diningphilosophers_release_2"] = func(ctx context.Context, variables map[string]any) (any, error) {
		input := graph.Release2Input{}
		if vars, ok := variables["input"].(map[string]any); ok {
			if id, ok := vars["aggregateId"].(string); ok {
				input.AggregateID = id
			}
		}
		return resolver.Release2(ctx, input)
	}
	resolvers["release2"] = resolvers["diningphilosophers_release_2"]

	resolvers["diningphilosophers_release_3"] = func(ctx context.Context, variables map[string]any) (any, error) {
		input := graph.Release3Input{}
		if vars, ok := variables["input"].(map[string]any); ok {
			if id, ok := vars["aggregateId"].(string); ok {
				input.AggregateID = id
			}
		}
		return resolver.Release3(ctx, input)
	}
	resolvers["release3"] = resolvers["diningphilosophers_release_3"]

	resolvers["diningphilosophers_release_4"] = func(ctx context.Context, variables map[string]any) (any, error) {
		input := graph.Release4Input{}
		if vars, ok := variables["input"].(map[string]any); ok {
			if id, ok := vars["aggregateId"].(string); ok {
				input.AggregateID = id
			}
		}
		return resolver.Release4(ctx, input)
	}
	resolvers["release4"] = resolvers["diningphilosophers_release_4"]

	// Events resolver (namespace for unified endpoint)
	resolvers["diningphilosophers_events"] = func(ctx context.Context, variables map[string]any) (any, error) {
		aggID, _ := variables["aggregateId"].(string)
		var from *int
		if f, ok := variables["from"].(float64); ok {
			fi := int(f)
			from = &fi
		}
		return resolver.Events(ctx, aggID, from)
	}
	resolvers["events"] = resolvers["diningphilosophers_events"]
	resolvers["diningphilosophersEvents"] = resolvers["diningphilosophers_events"]

	return resolvers
}
