load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "engine",
    srcs = ["engine.go"],
    importpath = "github.com/pflow-xyz/petri-pilot/pkg/runtime/engine",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/dsl",
        "//pkg/metamodel",
        "@com_github_pflow_xyz_go_pflow//eventsource",
    ],
)

go_test(
    name = "engine_test",
    srcs = ["marking_guard_test.go"],
    embed = [":engine"],
    deps = [
        "//pkg/dsl",
        "//pkg/metamodel",
    ],
)
