// Code generated by petri-pilot. DO NOT EDIT.

package vetclinic

import (
	"time"
)

// PatientArrivesedEvent is emitted when the patient_arrives transition fires.
type PatientArrivesedEvent struct {
	AggregateId string    `json:"aggregate_id"`
	Timestamp   time.Time `json:"timestamp"`
}

// EventType returns the event type identifier.
func (e PatientArrivesedEvent) EventType() string {
	return "PatientArrivesed"
}

// EmergencyArrivesedEvent is emitted when the emergency_arrives transition fires.
type EmergencyArrivesedEvent struct {
	AggregateId string    `json:"aggregate_id"`
	Timestamp   time.Time `json:"timestamp"`
}

// EventType returns the event type identifier.
func (e EmergencyArrivesedEvent) EventType() string {
	return "EmergencyArrivesed"
}

// TriageToExamedEvent is emitted when the triage_to_exam transition fires.
type TriageToExamedEvent struct {
	AggregateId string    `json:"aggregate_id"`
	Timestamp   time.Time `json:"timestamp"`
}

// EventType returns the event type identifier.
func (e TriageToExamedEvent) EventType() string {
	return "TriageToExamed"
}

// TriageToTechedEvent is emitted when the triage_to_tech transition fires.
type TriageToTechedEvent struct {
	AggregateId string    `json:"aggregate_id"`
	Timestamp   time.Time `json:"timestamp"`
}

// EventType returns the event type identifier.
func (e TriageToTechedEvent) EventType() string {
	return "TriageToTeched"
}

// TriageToSurgeryedEvent is emitted when the triage_to_surgery transition fires.
type TriageToSurgeryedEvent struct {
	AggregateId string    `json:"aggregate_id"`
	Timestamp   time.Time `json:"timestamp"`
}

// EventType returns the event type identifier.
func (e TriageToSurgeryedEvent) EventType() string {
	return "TriageToSurgeryed"
}

// TriageToDentaledEvent is emitted when the triage_to_dental transition fires.
type TriageToDentaledEvent struct {
	AggregateId string    `json:"aggregate_id"`
	Timestamp   time.Time `json:"timestamp"`
}

// EventType returns the event type identifier.
func (e TriageToDentaledEvent) EventType() string {
	return "TriageToDentaled"
}

// TriageToDiagedEvent is emitted when the triage_to_diag transition fires.
type TriageToDiagedEvent struct {
	AggregateId string    `json:"aggregate_id"`
	Timestamp   time.Time `json:"timestamp"`
}

// EventType returns the event type identifier.
func (e TriageToDiagedEvent) EventType() string {
	return "TriageToDiaged"
}

// StartWellnessedEvent is emitted when the start_wellness transition fires.
type StartWellnessedEvent struct {
	AggregateId string    `json:"aggregate_id"`
	Timestamp   time.Time `json:"timestamp"`
}

// EventType returns the event type identifier.
func (e StartWellnessedEvent) EventType() string {
	return "StartWellnessed"
}

// FinishWellnessedEvent is emitted when the finish_wellness transition fires.
type FinishWellnessedEvent struct {
	AggregateId string    `json:"aggregate_id"`
	Timestamp   time.Time `json:"timestamp"`
}

// EventType returns the event type identifier.
func (e FinishWellnessedEvent) EventType() string {
	return "FinishWellnessed"
}

// StartSickedEvent is emitted when the start_sick transition fires.
type StartSickedEvent struct {
	AggregateId string    `json:"aggregate_id"`
	Timestamp   time.Time `json:"timestamp"`
}

// EventType returns the event type identifier.
func (e StartSickedEvent) EventType() string {
	return "StartSicked"
}

// FinishSickedEvent is emitted when the finish_sick transition fires.
type FinishSickedEvent struct {
	AggregateId string    `json:"aggregate_id"`
	Timestamp   time.Time `json:"timestamp"`
}

// EventType returns the event type identifier.
func (e FinishSickedEvent) EventType() string {
	return "FinishSicked"
}

// StartVaccineedEvent is emitted when the start_vaccine transition fires.
type StartVaccineedEvent struct {
	AggregateId string    `json:"aggregate_id"`
	Timestamp   time.Time `json:"timestamp"`
}

// EventType returns the event type identifier.
func (e StartVaccineedEvent) EventType() string {
	return "StartVaccineed"
}

// FinishVaccineedEvent is emitted when the finish_vaccine transition fires.
type FinishVaccineedEvent struct {
	AggregateId string    `json:"aggregate_id"`
	Timestamp   time.Time `json:"timestamp"`
}

// EventType returns the event type identifier.
func (e FinishVaccineedEvent) EventType() string {
	return "FinishVaccineed"
}

// StartNailTrimedEvent is emitted when the start_nail_trim transition fires.
type StartNailTrimedEvent struct {
	AggregateId string    `json:"aggregate_id"`
	Timestamp   time.Time `json:"timestamp"`
}

// EventType returns the event type identifier.
func (e StartNailTrimedEvent) EventType() string {
	return "StartNailTrimed"
}

// FinishNailTrimedEvent is emitted when the finish_nail_trim transition fires.
type FinishNailTrimedEvent struct {
	AggregateId string    `json:"aggregate_id"`
	Timestamp   time.Time `json:"timestamp"`
}

// EventType returns the event type identifier.
func (e FinishNailTrimedEvent) EventType() string {
	return "FinishNailTrimed"
}

// StartWeightedEvent is emitted when the start_weight transition fires.
type StartWeightedEvent struct {
	AggregateId string    `json:"aggregate_id"`
	Timestamp   time.Time `json:"timestamp"`
}

// EventType returns the event type identifier.
func (e StartWeightedEvent) EventType() string {
	return "StartWeighted"
}

// FinishWeightedEvent is emitted when the finish_weight transition fires.
type FinishWeightedEvent struct {
	AggregateId string    `json:"aggregate_id"`
	Timestamp   time.Time `json:"timestamp"`
}

// EventType returns the event type identifier.
func (e FinishWeightedEvent) EventType() string {
	return "FinishWeighted"
}

// StartSutureedEvent is emitted when the start_suture transition fires.
type StartSutureedEvent struct {
	AggregateId string    `json:"aggregate_id"`
	Timestamp   time.Time `json:"timestamp"`
}

// EventType returns the event type identifier.
func (e StartSutureedEvent) EventType() string {
	return "StartSutureed"
}

// FinishSutureedEvent is emitted when the finish_suture transition fires.
type FinishSutureedEvent struct {
	AggregateId string    `json:"aggregate_id"`
	Timestamp   time.Time `json:"timestamp"`
}

// EventType returns the event type identifier.
func (e FinishSutureedEvent) EventType() string {
	return "FinishSutureed"
}

// StartSpayedEvent is emitted when the start_spay transition fires.
type StartSpayedEvent struct {
	AggregateId string    `json:"aggregate_id"`
	Timestamp   time.Time `json:"timestamp"`
}

// EventType returns the event type identifier.
func (e StartSpayedEvent) EventType() string {
	return "StartSpayed"
}

// FinishSpayedEvent is emitted when the finish_spay transition fires.
type FinishSpayedEvent struct {
	AggregateId string    `json:"aggregate_id"`
	Timestamp   time.Time `json:"timestamp"`
}

// EventType returns the event type identifier.
func (e FinishSpayedEvent) EventType() string {
	return "FinishSpayed"
}

// StartNeuteredEvent is emitted when the start_neuter transition fires.
type StartNeuteredEvent struct {
	AggregateId string    `json:"aggregate_id"`
	Timestamp   time.Time `json:"timestamp"`
}

// EventType returns the event type identifier.
func (e StartNeuteredEvent) EventType() string {
	return "StartNeutered"
}

// FinishNeuteredEvent is emitted when the finish_neuter transition fires.
type FinishNeuteredEvent struct {
	AggregateId string    `json:"aggregate_id"`
	Timestamp   time.Time `json:"timestamp"`
}

// EventType returns the event type identifier.
func (e FinishNeuteredEvent) EventType() string {
	return "FinishNeutered"
}

// StartDentaledEvent is emitted when the start_dental transition fires.
type StartDentaledEvent struct {
	AggregateId string    `json:"aggregate_id"`
	Timestamp   time.Time `json:"timestamp"`
}

// EventType returns the event type identifier.
func (e StartDentaledEvent) EventType() string {
	return "StartDentaled"
}

// FinishDentaledEvent is emitted when the finish_dental transition fires.
type FinishDentaledEvent struct {
	AggregateId string    `json:"aggregate_id"`
	Timestamp   time.Time `json:"timestamp"`
}

// EventType returns the event type identifier.
func (e FinishDentaledEvent) EventType() string {
	return "FinishDentaled"
}

// StartXrayedEvent is emitted when the start_xray transition fires.
type StartXrayedEvent struct {
	AggregateId string    `json:"aggregate_id"`
	Timestamp   time.Time `json:"timestamp"`
}

// EventType returns the event type identifier.
func (e StartXrayedEvent) EventType() string {
	return "StartXrayed"
}

// FinishXrayedEvent is emitted when the finish_xray transition fires.
type FinishXrayedEvent struct {
	AggregateId string    `json:"aggregate_id"`
	Timestamp   time.Time `json:"timestamp"`
}

// EventType returns the event type identifier.
func (e FinishXrayedEvent) EventType() string {
	return "FinishXrayed"
}

// StartBloodworkedEvent is emitted when the start_bloodwork transition fires.
type StartBloodworkedEvent struct {
	AggregateId string    `json:"aggregate_id"`
	Timestamp   time.Time `json:"timestamp"`
}

// EventType returns the event type identifier.
func (e StartBloodworkedEvent) EventType() string {
	return "StartBloodworked"
}

// FinishBloodworkedEvent is emitted when the finish_bloodwork transition fires.
type FinishBloodworkedEvent struct {
	AggregateId string    `json:"aggregate_id"`
	Timestamp   time.Time `json:"timestamp"`
}

// EventType returns the event type identifier.
func (e FinishBloodworkedEvent) EventType() string {
	return "FinishBloodworked"
}

// StartLabedEvent is emitted when the start_lab transition fires.
type StartLabedEvent struct {
	AggregateId string    `json:"aggregate_id"`
	Timestamp   time.Time `json:"timestamp"`
}

// EventType returns the event type identifier.
func (e StartLabedEvent) EventType() string {
	return "StartLabed"
}

// FinishLabedEvent is emitted when the finish_lab transition fires.
type FinishLabedEvent struct {
	AggregateId string    `json:"aggregate_id"`
	Timestamp   time.Time `json:"timestamp"`
}

// EventType returns the event type identifier.
func (e FinishLabedEvent) EventType() string {
	return "FinishLabed"
}

// StartEmergencyedEvent is emitted when the start_emergency transition fires.
type StartEmergencyedEvent struct {
	AggregateId string    `json:"aggregate_id"`
	Timestamp   time.Time `json:"timestamp"`
}

// EventType returns the event type identifier.
func (e StartEmergencyedEvent) EventType() string {
	return "StartEmergencyed"
}

// FinishEmergencyedEvent is emitted when the finish_emergency transition fires.
type FinishEmergencyedEvent struct {
	AggregateId string    `json:"aggregate_id"`
	Timestamp   time.Time `json:"timestamp"`
}

// EventType returns the event type identifier.
func (e FinishEmergencyedEvent) EventType() string {
	return "FinishEmergencyed"
}

// StartCheckoutedEvent is emitted when the start_checkout transition fires.
type StartCheckoutedEvent struct {
	AggregateId string    `json:"aggregate_id"`
	Timestamp   time.Time `json:"timestamp"`
}

// EventType returns the event type identifier.
func (e StartCheckoutedEvent) EventType() string {
	return "StartCheckouted"
}

// FinishCheckoutedEvent is emitted when the finish_checkout transition fires.
type FinishCheckoutedEvent struct {
	AggregateId string    `json:"aggregate_id"`
	Timestamp   time.Time `json:"timestamp"`
}

// EventType returns the event type identifier.
func (e FinishCheckoutedEvent) EventType() string {
	return "FinishCheckouted"
}

// FinishRecoveryedEvent is emitted when the finish_recovery transition fires.
type FinishRecoveryedEvent struct {
	AggregateId string    `json:"aggregate_id"`
	Timestamp   time.Time `json:"timestamp"`
}

// EventType returns the event type identifier.
func (e FinishRecoveryedEvent) EventType() string {
	return "FinishRecoveryed"
}

// AbandonExamedEvent is emitted when the abandon_exam transition fires.
type AbandonExamedEvent struct {
	AggregateId string    `json:"aggregate_id"`
	Timestamp   time.Time `json:"timestamp"`
}

// EventType returns the event type identifier.
func (e AbandonExamedEvent) EventType() string {
	return "AbandonExamed"
}

// AbandonTechedEvent is emitted when the abandon_tech transition fires.
type AbandonTechedEvent struct {
	AggregateId string    `json:"aggregate_id"`
	Timestamp   time.Time `json:"timestamp"`
}

// EventType returns the event type identifier.
func (e AbandonTechedEvent) EventType() string {
	return "AbandonTeched"
}

// AbandonDiagedEvent is emitted when the abandon_diag transition fires.
type AbandonDiagedEvent struct {
	AggregateId string    `json:"aggregate_id"`
	Timestamp   time.Time `json:"timestamp"`
}

// EventType returns the event type identifier.
func (e AbandonDiagedEvent) EventType() string {
	return "AbandonDiaged"
}

// AbandonSurgeryedEvent is emitted when the abandon_surgery transition fires.
type AbandonSurgeryedEvent struct {
	AggregateId string    `json:"aggregate_id"`
	Timestamp   time.Time `json:"timestamp"`
}

// EventType returns the event type identifier.
func (e AbandonSurgeryedEvent) EventType() string {
	return "AbandonSurgeryed"
}

// AbandonDentaledEvent is emitted when the abandon_dental transition fires.
type AbandonDentaledEvent struct {
	AggregateId string    `json:"aggregate_id"`
	Timestamp   time.Time `json:"timestamp"`
}

// EventType returns the event type identifier.
func (e AbandonDentaledEvent) EventType() string {
	return "AbandonDentaled"
}

// DivertEmergencyedEvent is emitted when the divert_emergency transition fires.
type DivertEmergencyedEvent struct {
	AggregateId string    `json:"aggregate_id"`
	Timestamp   time.Time `json:"timestamp"`
}

// EventType returns the event type identifier.
func (e DivertEmergencyedEvent) EventType() string {
	return "DivertEmergencyed"
}
