// Code generated by petri-pilot. DO NOT EDIT.

package vetclinic

import (
	"context"
	"testing"

	"github.com/pflow-xyz/go-pflow/eventsource"
)

func TestWorkflowConstants(t *testing.T) {
	// Verify place constants
	places := AllPlaces()
	if len(places) != 38 {
		t.Errorf("expected 38 places, got %d", len(places))
	}

	// Verify transition constants
	transitions := AllTransitions()
	if len(transitions) != 42 {
		t.Errorf("expected 42 transitions, got %d", len(transitions))
	}
}

func TestInitialPlaces(t *testing.T) {
	initial := InitialPlaces()
	_ = initial // suppress unused variable warning if no places have initial values
	if initial[PlaceDvmAvail] != 2 {
		t.Errorf("expected PlaceDvmAvail initial = 2, got %d", initial[PlaceDvmAvail])
	}
	if initial[PlaceRvtAvail] != 3 {
		t.Errorf("expected PlaceRvtAvail initial = 3, got %d", initial[PlaceRvtAvail])
	}
	if initial[PlaceReceptionistAvail] != 1 {
		t.Errorf("expected PlaceReceptionistAvail initial = 1, got %d", initial[PlaceReceptionistAvail])
	}
	if initial[PlaceExamRoomFree] != 4 {
		t.Errorf("expected PlaceExamRoomFree initial = 4, got %d", initial[PlaceExamRoomFree])
	}
	if initial[PlaceSurgeryFree] != 1 {
		t.Errorf("expected PlaceSurgeryFree initial = 1, got %d", initial[PlaceSurgeryFree])
	}
	if initial[PlaceDentalFree] != 1 {
		t.Errorf("expected PlaceDentalFree initial = 1, got %d", initial[PlaceDentalFree])
	}
	if initial[PlaceRadiologyFree] != 1 {
		t.Errorf("expected PlaceRadiologyFree initial = 1, got %d", initial[PlaceRadiologyFree])
	}
	if initial[PlaceTreatmentFree] != 3 {
		t.Errorf("expected PlaceTreatmentFree initial = 3, got %d", initial[PlaceTreatmentFree])
	}
	if initial[PlaceRecoveryFree] != 6 {
		t.Errorf("expected PlaceRecoveryFree initial = 6, got %d", initial[PlaceRecoveryFree])
	}
	if initial[PlaceLabFree] != 1 {
		t.Errorf("expected PlaceLabFree initial = 1, got %d", initial[PlaceLabFree])
	}
	if initial[PlaceSurgeryDay] != 1 {
		t.Errorf("expected PlaceSurgeryDay initial = 1, got %d", initial[PlaceSurgeryDay])
	}
}

func TestNewAggregate(t *testing.T) {
	agg := NewAggregate("")
	if agg.ID() == "" {
		t.Error("expected non-empty aggregate ID")
	}
	// Version starts at -1 before any events are applied
	if agg.Version() != -1 {
		t.Errorf("expected version -1, got %d", agg.Version())
	}
}

func TestAggregateWithID(t *testing.T) {
	agg := NewAggregate("test-123")
	if agg.ID() != "test-123" {
		t.Errorf("expected ID 'test-123', got %q", agg.ID())
	}
}

func TestInitialState(t *testing.T) {
	agg := NewAggregate("")
	places := agg.Places()
	_ = places // suppress unused variable warning if no places have initial values
	if places[PlaceDvmAvail] != 2 {
		t.Errorf("expected PlaceDvmAvail = 2, got %d", places[PlaceDvmAvail])
	}
	if places[PlaceRvtAvail] != 3 {
		t.Errorf("expected PlaceRvtAvail = 3, got %d", places[PlaceRvtAvail])
	}
	if places[PlaceReceptionistAvail] != 1 {
		t.Errorf("expected PlaceReceptionistAvail = 1, got %d", places[PlaceReceptionistAvail])
	}
	if places[PlaceExamRoomFree] != 4 {
		t.Errorf("expected PlaceExamRoomFree = 4, got %d", places[PlaceExamRoomFree])
	}
	if places[PlaceSurgeryFree] != 1 {
		t.Errorf("expected PlaceSurgeryFree = 1, got %d", places[PlaceSurgeryFree])
	}
	if places[PlaceDentalFree] != 1 {
		t.Errorf("expected PlaceDentalFree = 1, got %d", places[PlaceDentalFree])
	}
	if places[PlaceRadiologyFree] != 1 {
		t.Errorf("expected PlaceRadiologyFree = 1, got %d", places[PlaceRadiologyFree])
	}
	if places[PlaceTreatmentFree] != 3 {
		t.Errorf("expected PlaceTreatmentFree = 3, got %d", places[PlaceTreatmentFree])
	}
	if places[PlaceRecoveryFree] != 6 {
		t.Errorf("expected PlaceRecoveryFree = 6, got %d", places[PlaceRecoveryFree])
	}
	if places[PlaceLabFree] != 1 {
		t.Errorf("expected PlaceLabFree = 1, got %d", places[PlaceLabFree])
	}
	if places[PlaceSurgeryDay] != 1 {
		t.Errorf("expected PlaceSurgeryDay = 1, got %d", places[PlaceSurgeryDay])
	}
}

func TestEnabledTransitions(t *testing.T) {
	agg := NewAggregate("")
	enabled := agg.EnabledTransitions()

	// At least one transition should be enabled in initial state
	if len(enabled) == 0 {
		t.Log("Warning: no transitions enabled in initial state")
	}
}

func TestApplicationCreate(t *testing.T) {
	store := eventsource.NewMemoryStore()
	defer store.Close()

	app := NewApplication(store)
	ctx := context.Background()

	id, err := app.Create(ctx)
	if err != nil {
		t.Fatalf("Create failed: %v", err)
	}
	if id == "" {
		t.Error("expected non-empty ID")
	}
}

func TestApplicationLoadNewAggregate(t *testing.T) {
	store := eventsource.NewMemoryStore()
	defer store.Close()

	app := NewApplication(store)
	ctx := context.Background()

	id, _ := app.Create(ctx)
	agg, err := app.Load(ctx, id)
	if err != nil {
		t.Fatalf("Load failed: %v", err)
	}
	if agg.ID() != id {
		t.Errorf("expected ID %q, got %q", id, agg.ID())
	}
}

func TestFirstTransition(t *testing.T) {
	store := eventsource.NewMemoryStore()
	defer store.Close()

	app := NewApplication(store)
	ctx := context.Background()

	// Create new aggregate
	id, _ := app.Create(ctx)

	// Load and check enabled transitions
	agg, _ := app.Load(ctx, id)
	enabled := agg.EnabledTransitions()

	if len(enabled) == 0 {
		t.Skip("No transitions enabled in initial state")
	}

	// Try to execute the first enabled transition
	firstTransition := enabled[0]
	agg, err := app.Execute(ctx, id, firstTransition, nil)
	if err != nil {
		t.Fatalf("Execute %s failed: %v", firstTransition, err)
	}

	// Verify version is 0 (first event, 0-indexed)
	if agg.Version() != 0 {
		t.Errorf("expected version 0 after first transition, got %d", agg.Version())
	}
}

func TestCannotFireDisabledTransition(t *testing.T) {
	store := eventsource.NewMemoryStore()
	defer store.Close()

	app := NewApplication(store)
	ctx := context.Background()

	id, _ := app.Create(ctx)
	agg, _ := app.Load(ctx, id)

	// Find a transition that is NOT enabled
	allTransitions := AllTransitions()
	enabled := agg.EnabledTransitions()
	enabledSet := make(map[string]bool)
	for _, t := range enabled {
		enabledSet[t] = true
	}

	var disabledTransition string
	for _, t := range allTransitions {
		if !enabledSet[t] {
			disabledTransition = t
			break
		}
	}

	if disabledTransition == "" {
		t.Skip("All transitions are enabled in initial state")
	}

	// Try to execute a disabled transition
	_, err := app.Execute(ctx, id, disabledTransition, nil)
	if err == nil {
		t.Errorf("expected error when firing disabled transition %s", disabledTransition)
	}
}
