// Code generated by petri-pilot. DO NOT EDIT.

package vetclinic

// Place constants
const (
	PlaceDvmAvail          = "dvm_avail"
	PlaceRvtAvail          = "rvt_avail"
	PlaceReceptionistAvail = "receptionist_avail"
	PlaceExamRoomFree      = "exam_room_free"
	PlaceSurgeryFree       = "surgery_free"
	PlaceDentalFree        = "dental_free"
	PlaceRadiologyFree     = "radiology_free"
	PlaceTreatmentFree     = "treatment_free"
	PlaceRecoveryFree      = "recovery_free"
	PlaceLabFree           = "lab_free"
	PlaceSurgeryDay        = "surgery_day"
	PlaceArrival           = "arrival"
	PlaceWaitExam          = "wait_exam"
	PlaceWaitTech          = "wait_tech"
	PlaceWaitSurgery       = "wait_surgery"
	PlaceWaitDental        = "wait_dental"
	PlaceWaitDiag          = "wait_diag"
	PlaceWaitEmergency     = "wait_emergency"
	PlaceWaitLab           = "wait_lab"
	PlaceWaitCheckout      = "wait_checkout"
	PlaceInWellness        = "in_wellness"
	PlaceInSick            = "in_sick"
	PlaceInVaccine         = "in_vaccine"
	PlaceInNailTrim        = "in_nail_trim"
	PlaceInWeight          = "in_weight"
	PlaceInSuture          = "in_suture"
	PlaceInSpay            = "in_spay"
	PlaceInNeuter          = "in_neuter"
	PlaceInDental          = "in_dental"
	PlaceInXray            = "in_xray"
	PlaceInBloodwork       = "in_bloodwork"
	PlaceInLab             = "in_lab"
	PlaceInEmergency       = "in_emergency"
	PlaceCheckingOut       = "checking_out"
	PlaceInRecovery        = "in_recovery"
	PlaceDischarged        = "discharged"
	PlaceWalkedOut         = "walked_out"
	PlaceDiverted          = "diverted"
)

// Transition constants
const (
	TransitionPatientArrives   = "patient_arrives"
	TransitionEmergencyArrives = "emergency_arrives"
	TransitionTriageToExam     = "triage_to_exam"
	TransitionTriageToTech     = "triage_to_tech"
	TransitionTriageToSurgery  = "triage_to_surgery"
	TransitionTriageToDental   = "triage_to_dental"
	TransitionTriageToDiag     = "triage_to_diag"
	TransitionStartWellness    = "start_wellness"
	TransitionFinishWellness   = "finish_wellness"
	TransitionStartSick        = "start_sick"
	TransitionFinishSick       = "finish_sick"
	TransitionStartVaccine     = "start_vaccine"
	TransitionFinishVaccine    = "finish_vaccine"
	TransitionStartNailTrim    = "start_nail_trim"
	TransitionFinishNailTrim   = "finish_nail_trim"
	TransitionStartWeight      = "start_weight"
	TransitionFinishWeight     = "finish_weight"
	TransitionStartSuture      = "start_suture"
	TransitionFinishSuture     = "finish_suture"
	TransitionStartSpay        = "start_spay"
	TransitionFinishSpay       = "finish_spay"
	TransitionStartNeuter      = "start_neuter"
	TransitionFinishNeuter     = "finish_neuter"
	TransitionStartDental      = "start_dental"
	TransitionFinishDental     = "finish_dental"
	TransitionStartXray        = "start_xray"
	TransitionFinishXray       = "finish_xray"
	TransitionStartBloodwork   = "start_bloodwork"
	TransitionFinishBloodwork  = "finish_bloodwork"
	TransitionStartLab         = "start_lab"
	TransitionFinishLab        = "finish_lab"
	TransitionStartEmergency   = "start_emergency"
	TransitionFinishEmergency  = "finish_emergency"
	TransitionStartCheckout    = "start_checkout"
	TransitionFinishCheckout   = "finish_checkout"
	TransitionFinishRecovery   = "finish_recovery"
	TransitionAbandonExam      = "abandon_exam"
	TransitionAbandonTech      = "abandon_tech"
	TransitionAbandonDiag      = "abandon_diag"
	TransitionAbandonSurgery   = "abandon_surgery"
	TransitionAbandonDental    = "abandon_dental"
	TransitionDivertEmergency  = "divert_emergency"
)

// Event type constants
const (
	EventTypePatientArrives   = "PatientArrivesed"
	EventTypeEmergencyArrives = "EmergencyArrivesed"
	EventTypeTriageToExam     = "TriageToExamed"
	EventTypeTriageToTech     = "TriageToTeched"
	EventTypeTriageToSurgery  = "TriageToSurgeryed"
	EventTypeTriageToDental   = "TriageToDentaled"
	EventTypeTriageToDiag     = "TriageToDiaged"
	EventTypeStartWellness    = "StartWellnessed"
	EventTypeFinishWellness   = "FinishWellnessed"
	EventTypeStartSick        = "StartSicked"
	EventTypeFinishSick       = "FinishSicked"
	EventTypeStartVaccine     = "StartVaccineed"
	EventTypeFinishVaccine    = "FinishVaccineed"
	EventTypeStartNailTrim    = "StartNailTrimed"
	EventTypeFinishNailTrim   = "FinishNailTrimed"
	EventTypeStartWeight      = "StartWeighted"
	EventTypeFinishWeight     = "FinishWeighted"
	EventTypeStartSuture      = "StartSutureed"
	EventTypeFinishSuture     = "FinishSutureed"
	EventTypeStartSpay        = "StartSpayed"
	EventTypeFinishSpay       = "FinishSpayed"
	EventTypeStartNeuter      = "StartNeutered"
	EventTypeFinishNeuter     = "FinishNeutered"
	EventTypeStartDental      = "StartDentaled"
	EventTypeFinishDental     = "FinishDentaled"
	EventTypeStartXray        = "StartXrayed"
	EventTypeFinishXray       = "FinishXrayed"
	EventTypeStartBloodwork   = "StartBloodworked"
	EventTypeFinishBloodwork  = "FinishBloodworked"
	EventTypeStartLab         = "StartLabed"
	EventTypeFinishLab        = "FinishLabed"
	EventTypeStartEmergency   = "StartEmergencyed"
	EventTypeFinishEmergency  = "FinishEmergencyed"
	EventTypeStartCheckout    = "StartCheckouted"
	EventTypeFinishCheckout   = "FinishCheckouted"
	EventTypeFinishRecovery   = "FinishRecoveryed"
	EventTypeAbandonExam      = "AbandonExamed"
	EventTypeAbandonTech      = "AbandonTeched"
	EventTypeAbandonDiag      = "AbandonDiaged"
	EventTypeAbandonSurgery   = "AbandonSurgeryed"
	EventTypeAbandonDental    = "AbandonDentaled"
	EventTypeDivertEmergency  = "DivertEmergencyed"
)

// InitialPlaces returns the initial token distribution for new aggregates.
func InitialPlaces() map[string]int {
	return map[string]int{
		PlaceDvmAvail:          2,
		PlaceRvtAvail:          3,
		PlaceReceptionistAvail: 1,
		PlaceExamRoomFree:      4,
		PlaceSurgeryFree:       1,
		PlaceDentalFree:        1,
		PlaceRadiologyFree:     1,
		PlaceTreatmentFree:     3,
		PlaceRecoveryFree:      6,
		PlaceLabFree:           1,
		PlaceSurgeryDay:        1,
	}
}

// AllPlaces returns all place IDs in the workflow.
func AllPlaces() []string {
	return []string{
		PlaceDvmAvail,
		PlaceRvtAvail,
		PlaceReceptionistAvail,
		PlaceExamRoomFree,
		PlaceSurgeryFree,
		PlaceDentalFree,
		PlaceRadiologyFree,
		PlaceTreatmentFree,
		PlaceRecoveryFree,
		PlaceLabFree,
		PlaceSurgeryDay,
		PlaceArrival,
		PlaceWaitExam,
		PlaceWaitTech,
		PlaceWaitSurgery,
		PlaceWaitDental,
		PlaceWaitDiag,
		PlaceWaitEmergency,
		PlaceWaitLab,
		PlaceWaitCheckout,
		PlaceInWellness,
		PlaceInSick,
		PlaceInVaccine,
		PlaceInNailTrim,
		PlaceInWeight,
		PlaceInSuture,
		PlaceInSpay,
		PlaceInNeuter,
		PlaceInDental,
		PlaceInXray,
		PlaceInBloodwork,
		PlaceInLab,
		PlaceInEmergency,
		PlaceCheckingOut,
		PlaceInRecovery,
		PlaceDischarged,
		PlaceWalkedOut,
		PlaceDiverted,
	}
}

// AllTransitions returns all transition IDs in the workflow.
func AllTransitions() []string {
	return []string{
		TransitionPatientArrives,
		TransitionEmergencyArrives,
		TransitionTriageToExam,
		TransitionTriageToTech,
		TransitionTriageToSurgery,
		TransitionTriageToDental,
		TransitionTriageToDiag,
		TransitionStartWellness,
		TransitionFinishWellness,
		TransitionStartSick,
		TransitionFinishSick,
		TransitionStartVaccine,
		TransitionFinishVaccine,
		TransitionStartNailTrim,
		TransitionFinishNailTrim,
		TransitionStartWeight,
		TransitionFinishWeight,
		TransitionStartSuture,
		TransitionFinishSuture,
		TransitionStartSpay,
		TransitionFinishSpay,
		TransitionStartNeuter,
		TransitionFinishNeuter,
		TransitionStartDental,
		TransitionFinishDental,
		TransitionStartXray,
		TransitionFinishXray,
		TransitionStartBloodwork,
		TransitionFinishBloodwork,
		TransitionStartLab,
		TransitionFinishLab,
		TransitionStartEmergency,
		TransitionFinishEmergency,
		TransitionStartCheckout,
		TransitionFinishCheckout,
		TransitionFinishRecovery,
		TransitionAbandonExam,
		TransitionAbandonTech,
		TransitionAbandonDiag,
		TransitionAbandonSurgery,
		TransitionAbandonDental,
		TransitionDivertEmergency,
	}
}
