-- Migration: 001_init_enzymekinetics
-- Generated by petri-pilot. DO NOT EDIT.
--
-- Event store schema for enzyme-kinetics workflow

-- Events table: append-only event log
CREATE TABLE IF NOT EXISTS events (
    id TEXT PRIMARY KEY,
    stream_id TEXT NOT NULL,
    type TEXT NOT NULL,
    version INTEGER NOT NULL,
    data TEXT NOT NULL,  -- JSON
    metadata TEXT,       -- JSON, optional
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(stream_id, version)
);

-- Indexes for common query patterns
CREATE INDEX IF NOT EXISTS idx_events_stream_id ON events(stream_id);
CREATE INDEX IF NOT EXISTS idx_events_stream_version ON events(stream_id, version);
CREATE INDEX IF NOT EXISTS idx_events_type ON events(type);
CREATE INDEX IF NOT EXISTS idx_events_timestamp ON events(timestamp);

-- Snapshots table: periodic aggregate state snapshots for faster replay
CREATE TABLE IF NOT EXISTS snapshots (
    stream_id TEXT PRIMARY KEY,
    version INTEGER NOT NULL,
    state TEXT NOT NULL,  -- JSON
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Projection: enzyme-kinetics aggregate state
-- Denormalized view for fast reads
CREATE TABLE IF NOT EXISTS "enzymekinetics_state" (
    id TEXT PRIMARY KEY,
    version INTEGER NOT NULL DEFAULT 0,
    "substrate" INTEGER DEFAULT 0,
    "enzyme" INTEGER DEFAULT 0,
    "complex" INTEGER DEFAULT 0,
    "product" INTEGER DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS "idx_enzymekinetics_state_updated" ON "enzymekinetics_state"(updated_at);

-- Place tokens tracking (Petri net state)
CREATE TABLE IF NOT EXISTS "enzymekinetics_places" (
    aggregate_id TEXT NOT NULL,
    place_id TEXT NOT NULL,
    tokens INTEGER NOT NULL DEFAULT 0,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (aggregate_id, place_id)
);

-- Event type constants for reference:
-- Binded
-- Unbinded
-- Catalyzeed

-- Place constants for reference:
-- substrate: Substrate molecules (S)
-- enzyme: Free enzyme molecules (E)
-- complex: Enzyme-substrate complex (ES)
-- product: Product molecules (P)

-- Transition constants for reference:
-- bind: Substrate binds to enzyme forming complex (rate k1)
-- unbind: Complex dissociates back to substrate and enzyme (rate k-1)
-- catalyze: Complex converts substrate to product, releasing enzyme (rate kcat)
