// Code generated by petri-pilot. DO NOT EDIT.

package stoplight

import (
	"context"
	"encoding/json"
	"net/http"

	"github.com/pflow-xyz/go-pflow/eventsource"
	"github.com/pflow-xyz/petri-pilot/examples/stoplight/graph"
	"github.com/pflow-xyz/petri-pilot/pkg/serve"
)

// GraphQLConfig holds the GraphQL server configuration.
var GraphQLConfig = struct {
	Path       string
	Playground bool
}{
	Path:       "/graphql",
	Playground: true,
}

// GraphQLHandler creates the GraphQL HTTP handler.
func GraphQLHandler(app *Application) http.HandlerFunc {
	resolver := graph.NewResolver(&graphQLApp{app: app})
	h := &graphQLHandler{resolver: resolver}
	return h.ServeHTTP
}

// PlaygroundHandler serves the GraphQL Playground UI.
func PlaygroundHandler() http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "text/html; charset=utf-8")
		w.Write([]byte(playgroundHTML))
	}
}

var playgroundHTML = "<!DOCTYPE html>\n" +
	"<html>\n" +
	"<head>\n" +
	"  <title>stoplight GraphQL Playground</title>\n" +
	"  <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/graphql-playground-react/build/static/css/index.css\" />\n" +
	"  <link rel=\"shortcut icon\" href=\"https://cdn.jsdelivr.net/npm/graphql-playground-react/build/favicon.png\" />\n" +
	"  <script src=\"https://cdn.jsdelivr.net/npm/graphql-playground-react/build/static/js/middleware.js\"></script>\n" +
	"</head>\n" +
	"<body>\n" +
	"  <div id=\"root\"></div>\n" +
	"  <script>\n" +
	"    window.addEventListener('load', function() {\n" +
	"      GraphQLPlayground.init(document.getElementById('root'), {\n" +
	"        endpoint: '/graphql',\n" +
	"        settings: {\n" +
	"          'editor.theme': 'dark',\n" +
	"          'editor.fontFamily': \"'Source Code Pro', 'Consolas', 'Inconsolata', 'Droid Sans Mono', 'Monaco', monospace\",\n" +
	"          'editor.fontSize': 14,\n" +
	"          'request.credentials': 'same-origin'\n" +
	"        }\n" +
	"      })\n" +
	"    })\n" +
	"  </script>\n" +
	"</body>\n" +
	"</html>\n"

// graphQLApp wraps Application to implement the resolver interface.
type graphQLApp struct {
	app *Application
}

func (a *graphQLApp) Create(ctx context.Context) (string, error) {
	return a.app.Create(ctx)
}

func (a *graphQLApp) Load(ctx context.Context, id string) (graph.Aggregate, error) {
	return a.app.Load(ctx, id)
}

func (a *graphQLApp) GetState(ctx context.Context, id string) (graph.Aggregate, error) {
	return a.app.GetState(ctx, id)
}

func (a *graphQLApp) Execute(ctx context.Context, id, transition string, data map[string]any) (graph.Aggregate, error) {
	return a.app.Execute(ctx, id, transition, data)
}

func (a *graphQLApp) HealthCheck(ctx context.Context) error {
	return a.app.HealthCheck(ctx)
}

func (a *graphQLApp) GetStore() eventsource.Store {
	return a.app.store
}

// graphQLHandler implements a simple GraphQL HTTP handler.
type graphQLHandler struct {
	resolver *graph.Resolver
}

func (h *graphQLHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return
	}

	var req struct {
		Query         string                 `json:"query"`
		OperationName string                 `json:"operationName"`
		Variables     map[string]interface{} `json:"variables"`
	}

	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	// Execute the GraphQL operation
	result := h.executeGraphQL(r.Context(), req.Query, req.OperationName, req.Variables)

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(result)
}

func (h *graphQLHandler) executeGraphQL(ctx context.Context, query, operationName string, variables map[string]interface{}) map[string]interface{} {
	// This is a simplified GraphQL executor
	// In production, use github.com/99designs/gqlgen for full spec compliance

	result := make(map[string]interface{})
	data := make(map[string]interface{})
	var errors []map[string]interface{}

	// Detect mutation vs query
	isMutation := containsString(query, "mutation")

	// Handle create mutation (supports both "createPackageName" and "package_create" naming)
	// Use matchField to avoid substring collision (e.g. "blogpost_create" vs "blogpost_create_post")
	if isMutation && (matchField(query, "createStoplight") || matchField(query, "stoplight_create")) {
		state, err := h.resolver.CreateStoplight(ctx)
		if err != nil {
			errors = append(errors, map[string]interface{}{"message": err.Error()})
		} else {
			// Return under whichever key the query used
			if matchField(query, "stoplight_create") {
				data["stoplight_create"] = state
			} else {
				data["createStoplight"] = state
			}
		}
	}

	// Handle transition mutations (supports both "transitionName" and "package_transition" naming)

	if isMutation && (containsString(query, "stoplight_go") || containsString(query, "go")) {
		input := graph.GoInput{}
		if vars, ok := variables["input"].(map[string]interface{}); ok {
			if id, ok := vars["aggregateId"].(string); ok {
				input.AggregateID = id
			}
		}
		res, err := h.resolver.Go(ctx, input)
		if err != nil {
			errors = append(errors, map[string]interface{}{"message": err.Error()})
		} else {
			// Return under whichever key the query used
			if containsString(query, "stoplight_go") {
				data["stoplight_go"] = res
			} else {
				data["go"] = res
			}
		}
	}

	if isMutation && (containsString(query, "stoplight_slow") || containsString(query, "slow")) {
		input := graph.SlowInput{}
		if vars, ok := variables["input"].(map[string]interface{}); ok {
			if id, ok := vars["aggregateId"].(string); ok {
				input.AggregateID = id
			}
		}
		res, err := h.resolver.Slow(ctx, input)
		if err != nil {
			errors = append(errors, map[string]interface{}{"message": err.Error()})
		} else {
			// Return under whichever key the query used
			if containsString(query, "stoplight_slow") {
				data["stoplight_slow"] = res
			} else {
				data["slow"] = res
			}
		}
	}

	if isMutation && (containsString(query, "stoplight_stop") || containsString(query, "stop")) {
		input := graph.StopInput{}
		if vars, ok := variables["input"].(map[string]interface{}); ok {
			if id, ok := vars["aggregateId"].(string); ok {
				input.AggregateID = id
			}
		}
		res, err := h.resolver.Stop(ctx, input)
		if err != nil {
			errors = append(errors, map[string]interface{}{"message": err.Error()})
		} else {
			// Return under whichever key the query used
			if containsString(query, "stoplight_stop") {
				data["stoplight_stop"] = res
			} else {
				data["stop"] = res
			}
		}
	}

	// Handle query for single aggregate
	if !isMutation && containsString(query, "stoplight(") {
		id := ""
		if idVar, ok := variables["id"].(string); ok {
			id = idVar
		}
		if id != "" {
			state, err := h.resolver.Stoplight(ctx, id)
			if err != nil {
				errors = append(errors, map[string]interface{}{"message": err.Error()})
			} else {
				data["stoplight"] = state
			}
		}
	}

	// Handle list query
	if !isMutation && containsString(query, "stoplightList") {
		var place *string
		var page, perPage *int
		if p, ok := variables["place"].(string); ok {
			place = &p
		}
		if p, ok := variables["page"].(float64); ok {
			pi := int(p)
			page = &pi
		}
		if p, ok := variables["perPage"].(float64); ok {
			pi := int(p)
			perPage = &pi
		}
		list, err := h.resolver.StoplightList(ctx, place, page, perPage)
		if err != nil {
			errors = append(errors, map[string]interface{}{"message": err.Error()})
		} else {
			data["stoplightList"] = list
		}
	}

	// Handle events query
	if !isMutation && containsString(query, "events(") {
		aggID := ""
		var from *int
		if id, ok := variables["aggregateId"].(string); ok {
			aggID = id
		}
		if f, ok := variables["from"].(float64); ok {
			fi := int(f)
			from = &fi
		}
		if aggID != "" {
			events, err := h.resolver.Events(ctx, aggID, from)
			if err != nil {
				errors = append(errors, map[string]interface{}{"message": err.Error()})
			} else {
				data["events"] = events
			}
		}
	}

	result["data"] = data
	if len(errors) > 0 {
		result["errors"] = errors
	}

	return result
}

func containsString(s, substr string) bool {
	return len(s) >= len(substr) && (s == substr || len(s) > 0 && containsStringHelper(s, substr))
}

func containsStringHelper(s, substr string) bool {
	for i := 0; i <= len(s)-len(substr); i++ {
		if s[i:i+len(substr)] == substr {
			return true
		}
	}
	return false
}

// matchField checks if a GraphQL field name appears in a query as a complete identifier.
// Unlike containsString, it ensures the match is not a prefix of a longer identifier.
// e.g. matchField("blogpost_create_post(...)", "blogpost_create") returns false.
func matchField(s, field string) bool {
	for i := 0; i <= len(s)-len(field); i++ {
		if s[i:i+len(field)] == field {
			// Check that the next character is not an identifier char
			if i+len(field) >= len(s) {
				return true
			}
			next := s[i+len(field)]
			if !isIdentChar(next) {
				return true
			}
		}
	}
	return false
}

func isIdentChar(c byte) bool {
	return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '_'
}

// GraphQLSchemaString is the GraphQL schema for this service.
// Used by the unified GraphQL endpoint to combine schemas.
var GraphQLSchemaString = `# GraphQL schema for stoplight

scalar Time

type Query {
  # Get aggregate state by ID
  stoplight(id: ID!): AggregateState

  # List aggregates with optional filtering
  stoplightList(place: String, page: Int, perPage: Int): AggregateList!

  # Event history for an aggregate
  events(aggregateId: ID!, from: Int): [Event!]!

  # Get state at specific version
  stateAtVersion(aggregateId: ID!, version: Int!): AggregateState
}

type Mutation {
  # Create a new stoplight instance
  createStoplight: AggregateState!

  # Red to green
  go(input: GoInput!): TransitionResult!

  # Green to yellow
  slow(input: SlowInput!): TransitionResult!

  # Yellow to red
  stop(input: StopInput!): TransitionResult!
}

# Aggregate state representation
type AggregateState {
  id: ID!
  version: Int!
  state: State!
  places: Places!
  enabledTransitions: [String!]!
}

# Workflow state with all places
type State {
  red: Int!
  green: Int!
  yellow: Int!
}

# Token counts for each place
type Places {
  red: Int!
  green: Int!
  yellow: Int!
}

# Result of a transition execution
type TransitionResult {
  success: Boolean!
  aggregateId: ID
  version: Int
  state: Places
  enabledTransitions: [String!]
  error: String
}

# Paginated list of aggregates
type AggregateList {
  items: [AggregateState!]!
  total: Int!
  page: Int!
  perPage: Int!
}


# Event record
type Event {
  id: ID!
  streamId: String!
  type: String!
  version: Int!
  timestamp: Time!
  data: String!
}


# Input types for mutations

input GoInput {
  aggregateId: ID!
}


input SlowInput {
  aggregateId: ID!
}


input StopInput {
  aggregateId: ID!
}

`

// GraphQLResolversMap returns a map of resolver functions for the unified GraphQL endpoint.
func GraphQLResolversMap(app *Application) map[string]serve.GraphQLResolver {
	gqlApp := &graphQLApp{app: app}
	resolver := graph.NewResolver(gqlApp)

	resolvers := make(map[string]serve.GraphQLResolver)

	// Query resolvers
	resolvers["stoplight"] = func(ctx context.Context, variables map[string]any) (any, error) {
		id, _ := variables["id"].(string)
		return resolver.Stoplight(ctx, id)
	}

	resolvers["stoplightList"] = func(ctx context.Context, variables map[string]any) (any, error) {
		var place *string
		var page, perPage *int
		if p, ok := variables["place"].(string); ok {
			place = &p
		}
		if p, ok := variables["page"].(float64); ok {
			pi := int(p)
			page = &pi
		}
		if p, ok := variables["perPage"].(float64); ok {
			pi := int(p)
			perPage = &pi
		}
		return resolver.StoplightList(ctx, place, page, perPage)
	}

	// Mutation resolvers (register both underscore and camelCase names for compatibility)
	resolvers["stoplight_create"] = func(ctx context.Context, _ map[string]any) (any, error) {
		return resolver.CreateStoplight(ctx)
	}
	resolvers["createStoplight"] = resolvers["stoplight_create"]

	resolvers["stoplight_go"] = func(ctx context.Context, variables map[string]any) (any, error) {
		input := graph.GoInput{}
		if vars, ok := variables["input"].(map[string]any); ok {
			if id, ok := vars["aggregateId"].(string); ok {
				input.AggregateID = id
			}
		}
		return resolver.Go(ctx, input)
	}
	resolvers["go"] = resolvers["stoplight_go"]

	resolvers["stoplight_slow"] = func(ctx context.Context, variables map[string]any) (any, error) {
		input := graph.SlowInput{}
		if vars, ok := variables["input"].(map[string]any); ok {
			if id, ok := vars["aggregateId"].(string); ok {
				input.AggregateID = id
			}
		}
		return resolver.Slow(ctx, input)
	}
	resolvers["slow"] = resolvers["stoplight_slow"]

	resolvers["stoplight_stop"] = func(ctx context.Context, variables map[string]any) (any, error) {
		input := graph.StopInput{}
		if vars, ok := variables["input"].(map[string]any); ok {
			if id, ok := vars["aggregateId"].(string); ok {
				input.AggregateID = id
			}
		}
		return resolver.Stop(ctx, input)
	}
	resolvers["stop"] = resolvers["stoplight_stop"]

	// Events resolver (namespace for unified endpoint)
	resolvers["stoplight_events"] = func(ctx context.Context, variables map[string]any) (any, error) {
		aggID, _ := variables["aggregateId"].(string)
		var from *int
		if f, ok := variables["from"].(float64); ok {
			fi := int(f)
			from = &fi
		}
		return resolver.Events(ctx, aggID, from)
	}
	resolvers["events"] = resolvers["stoplight_events"]
	resolvers["stoplightEvents"] = resolvers["stoplight_events"]

	return resolvers
}
