// Code generated by petri-pilot. DO NOT EDIT.

package stoplight

// Place constants
const (
	PlaceRed    = "red"
	PlaceGreen  = "green"
	PlaceYellow = "yellow"
)

// Transition constants
const (
	TransitionGo   = "go"
	TransitionSlow = "slow"
	TransitionStop = "stop"
)

// Event type constants
const (
	EventTypeGo   = "Go"
	EventTypeSlow = "Slowed"
	EventTypeStop = "Stoped"
)

// InitialPlaces returns the initial token distribution for new aggregates.
func InitialPlaces() map[string]int {
	return map[string]int{
		PlaceRed: 1,
	}
}

// AllPlaces returns all place IDs in the workflow.
func AllPlaces() []string {
	return []string{
		PlaceRed,
		PlaceGreen,
		PlaceYellow,
	}
}

// AllTransitions returns all transition IDs in the workflow.
func AllTransitions() []string {
	return []string{
		TransitionGo,
		TransitionSlow,
		TransitionStop,
	}
}
