name: Generate New App
description: Request a new application to be generated
title: "[App] "
labels: ["app-request", "copilot"]
assignees:
  - Copilot
body:
  - type: markdown
    attributes:
      value: |
        Describe your application and Copilot will generate it using petri-pilot.

  - type: textarea
    id: description
    attributes:
      label: Application Description
      description: Describe what your app should do in plain English
      placeholder: |
        A task management app where:
        - Users can create tasks with title and description
        - Tasks can be assigned to team members
        - Tasks move through states: todo → in_progress → review → done
        - Only admins can delete tasks
    validations:
      required: true

  - type: input
    id: name
    attributes:
      label: App Name
      description: Short name for the app (lowercase, hyphens ok)
      placeholder: task-manager
    validations:
      required: true

  - type: checkboxes
    id: features
    attributes:
      label: Features
      options:
        - label: Authentication (GitHub OAuth)
        - label: Role-based access control
        - label: Admin dashboard
        - label: Event history viewer
        - label: E2E tests (Playwright)
        - label: API tests

  - type: dropdown
    id: complexity
    attributes:
      label: Complexity
      options:
        - Simple (3-5 states)
        - Medium (5-10 states)
        - Complex (10+ states)
    validations:
      required: true
