// Code generated by petri-pilot. DO NOT EDIT.

package graph

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/pflow-xyz/go-pflow/eventsource"
)

// Resolver is the root resolver for GraphQL queries and mutations.
type Resolver struct {
	App interface {
		Create(ctx context.Context) (string, error)
		Load(ctx context.Context, id string) (Aggregate, error)
		GetState(ctx context.Context, id string) (Aggregate, error)
		Execute(ctx context.Context, id, transition string, data map[string]any) (Aggregate, error)
		HealthCheck(ctx context.Context) error
		GetStore() eventsource.Store
	}
}

// Aggregate interface for type safety
type Aggregate interface {
	ID() string
	Version() int
	State() any
	Places() map[string]int
	EnabledTransitions() []string
}

// NewResolver creates a new GraphQL resolver.
func NewResolver(app interface {
	Create(ctx context.Context) (string, error)
	Load(ctx context.Context, id string) (Aggregate, error)
	GetState(ctx context.Context, id string) (Aggregate, error)
	Execute(ctx context.Context, id, transition string, data map[string]any) (Aggregate, error)
	HealthCheck(ctx context.Context) error
	GetStore() eventsource.Store
}) *Resolver {
	return &Resolver{App: app}
}

// Query resolvers

// EnzymeKinetics returns the aggregate state by ID.
func (r *Resolver) EnzymeKinetics(ctx context.Context, id string) (*AggregateState, error) {
	agg, err := r.App.GetState(ctx, id)
	if err != nil {
		return nil, err
	}
	return aggregateToState(agg), nil
}

// EnzymeKineticsList returns a paginated list of aggregates.
func (r *Resolver) EnzymeKineticsList(ctx context.Context, place *string, page *int, perPage *int) (*AggregateList, error) {
	// Default pagination
	p := 1
	pp := 50
	if page != nil {
		p = *page
	}
	if perPage != nil {
		pp = *perPage
	}

	placeFilter := ""
	if place != nil {
		placeFilter = *place
	}
	// Admin features not enabled - return empty list
	_ = placeFilter
	return &AggregateList{
		Items:   []*AggregateState{},
		Total:   0,
		Page:    p,
		PerPage: pp,
	}, nil
}

// Events returns the event history for an aggregate.
func (r *Resolver) Events(ctx context.Context, aggregateID string, from *int) ([]*Event, error) {
	store := r.App.GetStore()
	fromVersion := 0
	if from != nil {
		fromVersion = *from
	}

	events, err := store.Read(ctx, aggregateID, fromVersion)
	if err != nil {
		return nil, err
	}

	result := make([]*Event, len(events))
	for i, evt := range events {
		data, _ := json.Marshal(evt.Data)
		result[i] = &Event{
			ID:        fmt.Sprintf("%s-%d", evt.StreamID, evt.Version),
			StreamID:  evt.StreamID,
			Type:      evt.Type,
			Version:   evt.Version,
			Timestamp: evt.Timestamp,
			Data:      string(data),
		}
	}

	return result, nil
}

// StateAtVersion returns the aggregate state at a specific version.
func (r *Resolver) StateAtVersion(ctx context.Context, aggregateID string, version int) (*AggregateState, error) {
	// This is a simplified implementation - would need aggregate rebuild logic
	agg, err := r.App.GetState(ctx, aggregateID)
	if err != nil {
		return nil, err
	}

	// TODO: Implement proper version replay
	state := aggregateToState(agg)
	state.Version = version
	return state, nil
}

// Mutation resolvers

// CreateEnzymekinetics creates a new aggregate instance.
func (r *Resolver) CreateEnzymekinetics(ctx context.Context) (*AggregateState, error) {
	id, err := r.App.Create(ctx)
	if err != nil {
		return nil, err
	}

	agg, err := r.App.Load(ctx, id)
	if err != nil {
		return nil, err
	}

	return aggregateToState(agg), nil
}

// Bind executes the bind transition.
func (r *Resolver) Bind(ctx context.Context, input BindInput) (*TransitionResult, error) {
	data := make(map[string]any)

	agg, err := r.App.Execute(ctx, input.AggregateID, "bind", data)
	if err != nil {
		errMsg := err.Error()
		return &TransitionResult{
			Success: false,
			Error:   &errMsg,
		}, nil
	}

	places := agg.Places()
	enabled := agg.EnabledTransitions()
	id := agg.ID()
	version := agg.Version()

	return &TransitionResult{
		Success:            true,
		AggregateID:        &id,
		Version:            &version,
		State:              placesToModel(places),
		EnabledTransitions: enabled,
	}, nil
}

// Unbind executes the unbind transition.
func (r *Resolver) Unbind(ctx context.Context, input UnbindInput) (*TransitionResult, error) {
	data := make(map[string]any)

	agg, err := r.App.Execute(ctx, input.AggregateID, "unbind", data)
	if err != nil {
		errMsg := err.Error()
		return &TransitionResult{
			Success: false,
			Error:   &errMsg,
		}, nil
	}

	places := agg.Places()
	enabled := agg.EnabledTransitions()
	id := agg.ID()
	version := agg.Version()

	return &TransitionResult{
		Success:            true,
		AggregateID:        &id,
		Version:            &version,
		State:              placesToModel(places),
		EnabledTransitions: enabled,
	}, nil
}

// Catalyze executes the catalyze transition.
func (r *Resolver) Catalyze(ctx context.Context, input CatalyzeInput) (*TransitionResult, error) {
	data := make(map[string]any)

	agg, err := r.App.Execute(ctx, input.AggregateID, "catalyze", data)
	if err != nil {
		errMsg := err.Error()
		return &TransitionResult{
			Success: false,
			Error:   &errMsg,
		}, nil
	}

	places := agg.Places()
	enabled := agg.EnabledTransitions()
	id := agg.ID()
	version := agg.Version()

	return &TransitionResult{
		Success:            true,
		AggregateID:        &id,
		Version:            &version,
		State:              placesToModel(places),
		EnabledTransitions: enabled,
	}, nil
}

// Helper functions

func aggregateToState(agg Aggregate) *AggregateState {
	places := agg.Places()
	return &AggregateState{
		ID:                 agg.ID(),
		Version:            agg.Version(),
		State:              stateToModel(agg.State()),
		Places:             placesToModel(places),
		EnabledTransitions: agg.EnabledTransitions(),
	}
}

func stateToModel(state any) *State {
	s := &State{}
	// Convert struct to map via JSON roundtrip for uniform field access
	m := stateToMap(state)
	if v, ok := m["substrate"]; ok {
		s.Substrate = v
	}
	if v, ok := m["enzyme"]; ok {
		s.Enzyme = v
	}
	if v, ok := m["complex"]; ok {
		s.Complex = v
	}
	if v, ok := m["product"]; ok {
		s.Product = v
	}
	return s
}

func stateToMap(state any) map[string]any {
	// Try direct map assertion first
	if m, ok := state.(map[string]any); ok {
		return m
	}
	// Fall back to JSON roundtrip for struct types
	b, err := json.Marshal(state)
	if err != nil {
		return nil
	}
	var m map[string]any
	if err := json.Unmarshal(b, &m); err != nil {
		return nil
	}
	return m
}

func placesToModel(places map[string]int) *Places {
	p := &Places{}
	if v, ok := places["substrate"]; ok {
		p.Substrate = v
	}
	if v, ok := places["enzyme"]; ok {
		p.Enzyme = v
	}
	if v, ok := places["complex"]; ok {
		p.Complex = v
	}
	if v, ok := places["product"]; ok {
		p.Product = v
	}
	return p
}

// GraphQL model types

type AggregateState struct {
	ID                 string   `json:"id"`
	Version            int      `json:"version"`
	State              *State   `json:"state"`
	Places             *Places  `json:"places"`
	EnabledTransitions []string `json:"enabledTransitions"`
}

type State struct {
	Substrate any `json:"substrate"`
	Enzyme    any `json:"enzyme"`
	Complex   any `json:"complex"`
	Product   any `json:"product"`
}

type Places struct {
	Substrate int `json:"substrate"`
	Enzyme    int `json:"enzyme"`
	Complex   int `json:"complex"`
	Product   int `json:"product"`
}

type TransitionResult struct {
	Success            bool     `json:"success"`
	AggregateID        *string  `json:"aggregateId"`
	Version            *int     `json:"version"`
	State              *Places  `json:"state"`
	EnabledTransitions []string `json:"enabledTransitions"`
	Error              *string  `json:"error"`
}

type AggregateList struct {
	Items   []*AggregateState `json:"items"`
	Total   int               `json:"total"`
	Page    int               `json:"page"`
	PerPage int               `json:"perPage"`
}

type Event struct {
	ID        string `json:"id"`
	StreamID  string `json:"streamId"`
	Type      string `json:"type"`
	Version   int    `json:"version"`
	Timestamp any    `json:"timestamp"`
	Data      string `json:"data"`
}

// Input types

type BindInput struct {
	AggregateID string
}

type UnbindInput struct {
	AggregateID string
}

type CatalyzeInput struct {
	AggregateID string
}
