package sim

import (
	"fmt"
	"sort"
	"testing"

	"github.com/pflow-xyz/go-pflow/metamodel"
)

// This file is `package sim` (not sim_test) deliberately: it needs refine()
// itself (unexported) to demonstrate, from the same code the report relies
// on, that 1-WL really does over-merge the constructed net below — the
// property this whole task exists to make visible rather than assert by
// prose.

// buildAsymmetricRingNet is the deliberately-constructed net this task asks
// for: a 3-cycle (PA0,TA0,PA1,TA1,PA2,TA2, arranged as a directed ring
// PA0->TA0->PA1->TA1->PA2->TA2->PA0) plus one isolated 2-cycle (Pb0<->Tb0,
// a place and transition that are each other's only neighbour).
//
// Every place shares one seed colour (Initial=0, Capacity=0, and
// ClassifySupply reports "queue" for all of them, since none is initially
// marked) and every transition shares one seed colour (the same default
// rate). From a PLACE's local point of view the two structures look
// identical: exactly one incoming "produce" edge from a T-coloured node and
// one outgoing "consume" edge to a T-coloured node — 1-WL only ever looks at
// labelled neighbour COLOURS, never node identity, so it cannot tell "my two
// edges go to two different, but identically-coloured, transitions" (the
// 3-ring) apart from "my two edges go to the SAME transition" (the 2-cycle).
// It therefore merges all four places into one colour, and all four
// transitions into one colour — a real instance of exactly the
// over-approximation ROADMAP.md Phase 6 names.
//
// The true automorphism group is generated by the 3-ring's rotation
// (PAi -> PA(i+1 mod 3), TAi -> TA(i+1 mod 3), Pb0/Tb0 fixed): orbits
// {PA0,PA1,PA2}, {TA0,TA1,TA2}, and two fixed points {Pb0}, {Tb0}. No
// automorphism can move Pb0 into the ring or vice versa, because Pb0's two
// edges point at the SAME node while every PAi's two edges point at
// DIFFERENT nodes — a graph-theoretic distinction 1-WL's colour-only view
// cannot see but an actual permutation-checking automorphism search can.
func buildAsymmetricRingNet() *metamodel.Model {
	m := &metamodel.Model{Name: "orbit-test-ring"}
	for i := 0; i < 3; i++ {
		m.Places = append(m.Places, metamodel.Place{ID: fmt.Sprintf("PA%d", i)})
		m.Transitions = append(m.Transitions, metamodel.Transition{ID: fmt.Sprintf("TA%d", i)})
	}
	for i := 0; i < 3; i++ {
		m.Arcs = append(m.Arcs,
			metamodel.Arc{From: fmt.Sprintf("PA%d", i), To: fmt.Sprintf("TA%d", i), Weight: 1},
			metamodel.Arc{From: fmt.Sprintf("TA%d", i), To: fmt.Sprintf("PA%d", (i+1)%3), Weight: 1},
		)
	}
	m.Places = append(m.Places, metamodel.Place{ID: "Pb0"})
	m.Transitions = append(m.Transitions, metamodel.Transition{ID: "Tb0"})
	m.Arcs = append(m.Arcs,
		metamodel.Arc{From: "Pb0", To: "Tb0", Weight: 1},
		metamodel.Arc{From: "Tb0", To: "Pb0", Weight: 1},
	)
	return m
}

// permutations enumerates every ordering of items, recursively. Fine for the
// 4-element lists this test needs (4! = 24 per bipartition half); not meant
// for anything larger.
func permutations(items []string) [][]string {
	if len(items) == 0 {
		return [][]string{{}}
	}
	var out [][]string
	for i := range items {
		rest := make([]string, 0, len(items)-1)
		rest = append(rest, items[:i]...)
		rest = append(rest, items[i+1:]...)
		for _, tail := range permutations(rest) {
			out = append(out, append([]string{items[i]}, tail...))
		}
	}
	return out
}

// arcKey is the exact tuple an automorphism must preserve: direction, arc
// type and weight (kineticity is uniform in this test net, so it is omitted
// rather than adding a check that can never fail here).
func arcKey(from, to string, a metamodel.Arc) string {
	w := a.Weight
	if w == 0 {
		w = 1
	}
	return fmt.Sprintf("%s>%s|%s|%d", from, to, a.Type, w)
}

// bruteForceAutomorphisms is the independent ground truth this test checks
// ExactOrbits against: every place<->place, transition<->transition bijection
// (the only kind that can possibly preserve a bipartite net's structure) is
// tried, by brute enumeration, and kept only if it maps every arc onto
// another arc exactly. This is the textbook definition of a graph
// automorphism, computed with no cleverness at all — the point of a
// brute-force cross-check is that it must not share a bug with the thing it
// verifies.
func bruteForceAutomorphisms(t *testing.T, m *metamodel.Model) []map[string]string {
	t.Helper()
	var places, transitions []string
	for _, p := range m.Places {
		places = append(places, p.ID)
	}
	for _, tr := range m.Transitions {
		transitions = append(transitions, tr.ID)
	}
	arcSet := map[string]bool{}
	for _, a := range m.Arcs {
		arcSet[arcKey(a.From, a.To, a)] = true
	}

	var out []map[string]string
	for _, pp := range permutations(places) {
		pmap := map[string]string{}
		for i, p := range places {
			pmap[p] = pp[i]
		}
		for _, tp := range permutations(transitions) {
			full := map[string]string{}
			for i, tr := range transitions {
				full[tr] = tp[i]
			}
			for k, v := range pmap {
				full[k] = v
			}
			ok := true
			for _, a := range m.Arcs {
				if !arcSet[arcKey(full[a.From], full[a.To], a)] {
					ok = false
					break
				}
			}
			if ok {
				out = append(out, full)
			}
		}
	}
	return out
}

// bruteForceOrbits turns the ground-truth automorphism list into orbits
// (connected components under "some automorphism maps u to v"), the same
// union-find reduction ExactOrbits itself uses — mirrored here independently
// so the test is not just re-running ExactOrbits' own machinery on itself.
func bruteForceOrbits(nodes []string, autos []map[string]string) [][]string {
	uf := newUnionFind(nodes)
	for _, g := range autos {
		for u, v := range g {
			if u != v {
				uf.union(u, v)
			}
		}
	}
	byRoot := map[string][]string{}
	for _, n := range nodes {
		r := uf.find(n)
		byRoot[r] = append(byRoot[r], n)
	}
	var out [][]string
	for _, members := range byRoot {
		if len(members) < 2 {
			continue
		}
		sort.Strings(members)
		out = append(out, members)
	}
	sort.Slice(out, func(i, j int) bool { return out[i][0] < out[j][0] })
	return out
}

func orbitsEqual(a, b [][]string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if len(a[i]) != len(b[i]) {
			return false
		}
		for j := range a[i] {
			if a[i][j] != b[i][j] {
				return false
			}
		}
	}
	return true
}

// TestExactOrbitsFindsKnownAutomorphism is this task's central verification:
// a net with a hand-designed, non-trivial automorphism group (the 3-ring's
// rotation) plus a deliberately asymmetric extra piece (the 2-cycle) that
// 1-WL cannot help but merge into the ring's colour class.
//
//  1. Confirms, via refine() itself (not a description of it), that 1-WL
//     really does merge all four places (and all four transitions) into one
//     colour each — the over-approximation this task exists to expose.
//  2. Cross-checks ExactOrbits' result against an independent brute-force
//     automorphism search (every permutation, checked by direct arc
//     comparison) — the actual proof this implementation is correct, not
//     just that it ran and produced output.
//  3. Confirms SameOrbit reports the WL colour class as split, naming the
//     ring and the singleton as separate groups, and that the ring's
//     rotation orbit is exactly {PA0,PA1,PA2} (never merged with Pb0).
func TestExactOrbitsFindsKnownAutomorphism(t *testing.T) {
	m := buildAsymmetricRingNet()

	// (1) The over-approximation, demonstrated rather than asserted: 1-WL's
	// own stable colouring puts every place in one class and every
	// transition in one class.
	colour := refine(m, true)
	placeColours := map[string]bool{}
	for _, p := range m.Places {
		placeColours[colour[p.ID]] = true
	}
	if len(placeColours) != 1 {
		t.Fatalf("test net construction failed its own premise: WL split places into %d colours, want 1 (all merged)", len(placeColours))
	}
	transColours := map[string]bool{}
	for _, tr := range m.Transitions {
		transColours[colour[tr.ID]] = true
	}
	if len(transColours) != 1 {
		t.Fatalf("test net construction failed its own premise: WL split transitions into %d colours, want 1 (all merged)", len(transColours))
	}

	// (2) Ground truth, by brute force.
	var nodes []string
	for _, p := range m.Places {
		nodes = append(nodes, p.ID)
	}
	for _, tr := range m.Transitions {
		nodes = append(nodes, tr.ID)
	}
	sort.Strings(nodes)
	autos := bruteForceAutomorphisms(t, m)
	wantOrbits := bruteForceOrbits(nodes, autos)

	report, err := ExactOrbits(m)
	if err != nil {
		t.Fatalf("ExactOrbits: %v", err)
	}
	t.Logf("brute-force found %d automorphisms (incl. identity contributions), ExactOrbits recorded %d generators, %d leaves",
		len(autos), report.Generators, report.Leaves)
	if !orbitsEqual(report.Orbits, wantOrbits) {
		t.Fatalf("orbits = %v, brute-force ground truth = %v", report.Orbits, wantOrbits)
	}

	// Exactly the expected shape: the ring is one orbit each side, the
	// singleton pair are fixed points (absent from Orbits entirely).
	wantShape := [][]string{{"PA0", "PA1", "PA2"}, {"TA0", "TA1", "TA2"}}
	if !orbitsEqual(report.Orbits, wantShape) {
		t.Fatalf("orbits = %v, want exactly %v", report.Orbits, wantShape)
	}

	// (3) The over-approximation, made visible: the WL colour class {all 4
	// places} does NOT survive as one orbit.
	same, groups := report.SameOrbit([]string{"PA0", "PA1", "PA2", "Pb0"})
	if same {
		t.Fatal("SameOrbit says the WL-merged class is one orbit; it must report the split (Pb0 is a fixed point, PA* is a 3-orbit)")
	}
	wantGroups := [][]string{{"PA0", "PA1", "PA2"}, {"Pb0"}}
	if !orbitsEqual(groups, wantGroups) {
		t.Fatalf("SameOrbit groups = %v, want %v", groups, wantGroups)
	}

	// And the case that SHOULD be confirmed: the ring's own three places are
	// exactly one orbit.
	same, _ = report.SameOrbit([]string{"PA0", "PA1", "PA2"})
	if !same {
		t.Fatal("SameOrbit should confirm PA0,PA1,PA2 as one orbit (the 3-ring rotation)")
	}
}

// TestExactOrbitsRigidNetHasNoGenerators pins the other end of the scale: a
// net with genuinely no symmetry (every place and transition individually
// distinguishable by its position) must report zero non-trivial orbits and
// zero generators, and its own WL colouring must already have found the
// same discrete partition — there is nothing here for either algorithm to
// get right or wrong about, which is the point of including it.
func TestExactOrbitsRigidNetHasNoGenerators(t *testing.T) {
	m := &metamodel.Model{Name: "orbit-test-chain"}
	// A straight chain p0 -> t0 -> p1 -> t1 -> p2, with strictly increasing
	// capacity so even quantitative colour cannot merge any two places.
	for i := 0; i < 3; i++ {
		m.Places = append(m.Places, metamodel.Place{ID: fmt.Sprintf("p%d", i), Capacity: i + 1})
	}
	for i := 0; i < 2; i++ {
		m.Transitions = append(m.Transitions, metamodel.Transition{ID: fmt.Sprintf("t%d", i)})
		m.Arcs = append(m.Arcs,
			metamodel.Arc{From: fmt.Sprintf("p%d", i), To: fmt.Sprintf("t%d", i), Weight: 1},
			metamodel.Arc{From: fmt.Sprintf("t%d", i), To: fmt.Sprintf("p%d", i+1), Weight: 1},
		)
	}
	report, err := ExactOrbits(m)
	if err != nil {
		t.Fatalf("ExactOrbits: %v", err)
	}
	if len(report.Orbits) != 0 || report.Generators != 0 {
		t.Fatalf("rigid chain reported orbits=%v generators=%d, want none", report.Orbits, report.Generators)
	}
}

// TestCanonicalModelIDIsIsomorphismInvariant is the other half of this
// task's verification: two models that differ ONLY by renaming every place
// and transition must collapse to the same CanonicalModelID, while
// modelstore's own content address (sha256 of canonical JSON) must differ —
// proving the new id is actually isomorphism-invariant rather than
// accidentally equal to the old one.
func TestCanonicalModelIDIsIsomorphismInvariant(t *testing.T) {
	a := &metamodel.Model{
		Name:   "canon-a",
		Places: []metamodel.Place{{ID: "p1", Initial: 5}, {ID: "p2"}},
		Transitions: []metamodel.Transition{
			{ID: "t1"},
		},
		Arcs: []metamodel.Arc{
			{From: "p1", To: "t1", Weight: 1},
			{From: "t1", To: "p2", Weight: 1},
		},
	}
	// Same net, same numeric attributes, every id renamed AND the name
	// itself changed — CanonicalModelID must not depend on Model.Name any
	// more than it depends on the place ids, since a name is exactly the
	// kind of relabelling this identifier is supposed to see through.
	b := &metamodel.Model{
		Name:   "canon-b-renamed",
		Places: []metamodel.Place{{ID: "queue-in", Initial: 5}, {ID: "queue-out"}},
		Transitions: []metamodel.Transition{
			{ID: "serve"},
		},
		Arcs: []metamodel.Arc{
			{From: "queue-in", To: "serve", Weight: 1},
			{From: "serve", To: "queue-out", Weight: 1},
		},
	}

	idA, err := CanonicalModelID(a)
	if err != nil {
		t.Fatalf("CanonicalModelID(a): %v", err)
	}
	idB, err := CanonicalModelID(b)
	if err != nil {
		t.Fatalf("CanonicalModelID(b): %v", err)
	}
	if idA != idB {
		t.Fatalf("CanonicalModelID differs across a pure renaming: %s vs %s", idA, idB)
	}

	// A model with a genuinely different attribute (p2 initially marked
	// instead of empty) must NOT collapse to the same canonical id — this
	// guards against a canonicalization that accidentally ignores the
	// initial marking entirely.
	c := &metamodel.Model{
		Name:        "canon-c-different",
		Places:      []metamodel.Place{{ID: "p1", Initial: 5}, {ID: "p2", Initial: 1}},
		Transitions: []metamodel.Transition{{ID: "t1"}},
		Arcs: []metamodel.Arc{
			{From: "p1", To: "t1", Weight: 1},
			{From: "t1", To: "p2", Weight: 1},
		},
	}
	idC, err := CanonicalModelID(c)
	if err != nil {
		t.Fatalf("CanonicalModelID(c): %v", err)
	}
	if idC == idA {
		t.Fatal("CanonicalModelID did not notice a different initial marking on p2")
	}
}
