package main

import (
	"crypto/sha256"
	"encoding/hex"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"github.com/pflow-xyz/petri-pilot/pkg/codegen/golang"
	"github.com/pflow-xyz/petri-pilot/services"
)

// Code generation must stay reproducible and stable while the Petri-net
// composition layer lands. Two properties are checked here:
//
//   - TestCodegenIsDeterministic: the same model generates the same bytes.
//   - TestCodegenOutputIsStable:  the generated bytes match a committed baseline.
//
// The baseline is a hash manifest captured from the generator, NOT a diff against
// the committed generated/ tree. That tree is not reproducible from the current
// templates — it predates several template changes (typed OpenAPI request
// schemas, the guest-login endpoint) — so diffing against it would report drift
// that has nothing to do with the change under test. Regenerating those 15 apps
// is a separate, deliberate decision; see TestCommittedAppsDivergeFromGenerator,
// which measures that gap without failing on it.
//
// If TestCodegenOutputIsStable fails, the change altered generated output. Either
// make it conditional on a feature no baseline model uses, or refresh the
// baseline deliberately:
//
//	go test ./cmd/petri-pilot -run TestCodegenOutputIsStable -update-baseline

var updateBaseline = flag.Bool("update-baseline", false,
	"rewrite testdata/codegen_baseline.txt from current generator output")

// freezeApps maps services/<model>.json to its generated/<pkg>/ directory.
//
// generated/marchmadness2026 is deliberately absent: it is hand-written, not
// template output.
var freezeApps = []struct{ model, pkg string }{
	{"coffeeshop", "coffeeshop"},
	{"dining-philosophers", "diningphilosophers"},
	{"enzyme-kinetics", "enzymekinetics"},
	{"galton-board", "galtonboard"},
	{"hiring-pipeline", "hiringpipeline"},
	{"knapsack", "knapsack"},
	{"loan-approval", "loanapproval"},
	{"predator-prey", "predatorprey"},
	{"producer-consumer", "producerconsumer"},
	{"stoplight", "stoplight"},
	{"tcp-handshake", "tcphandshake"},
	{"texas-holdem", "texasholdem"},
	{"thermostat", "thermostat"},
	{"tic-tac-toe", "tictactoe"},
}

const baselinePath = "testdata/codegen_baseline.txt"

func repoRoot(t *testing.T) string {
	t.Helper()
	// Under Bazel the test runs from a runfiles tree; fall back to walking up
	// from the package dir for plain `go test`.
	if dir := os.Getenv("TEST_SRCDIR"); dir != "" {
		if ws := os.Getenv("TEST_WORKSPACE"); ws != "" {
			return filepath.Join(dir, ws)
		}
	}
	wd, err := os.Getwd()
	if err != nil {
		t.Fatalf("getwd: %v", err)
	}
	for dir := wd; dir != "/"; dir = filepath.Dir(dir) {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
	}
	t.Fatalf("could not locate repo root from %s", wd)
	return ""
}

// regenerate reproduces the invocation the committed apps were built with:
//
//	petri-pilot codegen -submodule -bazel -pkg <pkg> -o generated/<pkg> services/<model>.json
//
// with -tests and -infra at their default true. It mirrors cmdCodegen's option
// construction (main.go:642-688) rather than shelling out, so a failure points at
// the generator instead of at the CLI.
func regenerate(t *testing.T, model, pkg string) map[string][]byte {
	t.Helper()

	// Read the embedded copy rather than services/*.json on disk: it keeps the
	// test hermetic under Bazel's sandbox with no data deps, and it is the same
	// bytes the serving binary uses.
	data, err := services.Get(model)
	if err != nil {
		t.Fatalf("read model: %v", err)
	}

	m, app, err := parseModelWithExtensions(data)
	if err != nil {
		t.Fatalf("parse model: %v", err)
	}
	hasExtensions := app.HasAdmin() || app.HasNavigation() || app.HasRoles() || app.HasViews() ||
		app.HasGraphQL() || app.HasDebug()

	outDir := "generated/" + pkg
	gen, err := golang.New(golang.Options{
		OutputDir:    outDir,
		ModulePath:   "github.com/pflow-xyz/petri-pilot/" + outDir,
		PackageName:  pkg,
		IncludeTests: true,
		IncludeInfra: true,
		IncludeBazel: true,
		AsSubmodule:  true,
	})
	if err != nil {
		t.Fatalf("new generator: %v", err)
	}

	var files []golang.GeneratedFile
	if hasExtensions {
		files, err = gen.GenerateFilesFromApp(app)
	} else {
		files, err = gen.GenerateFiles(m)
	}
	if err != nil {
		t.Fatalf("generate: %v", err)
	}

	out := make(map[string][]byte, len(files))
	for _, f := range files {
		out[f.Name] = f.Content
	}
	return out
}

// generateAll returns "<pkg>/<file>" → sha256 across every baseline app.
func generateAll(t *testing.T) map[string]string {
	t.Helper()
	sums := map[string]string{}
	for _, app := range freezeApps {
		for name, content := range regenerate(t, app.model, app.pkg) {
			sum := sha256.Sum256(content)
			sums[app.pkg+"/"+name] = hex.EncodeToString(sum[:])
		}
	}
	return sums
}

func readBaseline(t *testing.T, root string) map[string]string {
	t.Helper()
	data, err := os.ReadFile(filepath.Join(root, "cmd", "petri-pilot", baselinePath))
	if err != nil {
		t.Fatalf("read baseline (create it with -update-baseline): %v", err)
	}
	want := map[string]string{}
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		parts := strings.Fields(line)
		if len(parts) != 2 {
			t.Fatalf("malformed baseline line: %q", line)
		}
		want[parts[0]] = parts[1]
	}
	return want
}

func writeBaseline(t *testing.T, root string, sums map[string]string) {
	t.Helper()
	names := make([]string, 0, len(sums))
	for name := range sums {
		names = append(names, name)
	}
	sort.Strings(names)

	var b strings.Builder
	b.WriteString("# sha256 of every file petri-pilot's Go generator emits for services/*.json,\n")
	b.WriteString("# using: codegen -submodule -bazel -pkg <pkg> -o generated/<pkg>\n")
	b.WriteString("# Refresh deliberately: go test ./cmd/petri-pilot -run TestCodegenOutputIsStable -update-baseline\n")
	for _, name := range names {
		fmt.Fprintf(&b, "%s %s\n", name, sums[name])
	}

	path := filepath.Join(root, "cmd", "petri-pilot", baselinePath)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("mkdir testdata: %v", err)
	}
	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		t.Fatalf("write baseline: %v", err)
	}
	t.Logf("wrote %d hashes to %s", len(names), baselinePath)
}

func TestCodegenOutputIsStable(t *testing.T) {
	root := repoRoot(t)
	got := generateAll(t)

	if *updateBaseline {
		writeBaseline(t, root, got)
		return
	}

	want := readBaseline(t, root)
	for name, wantSum := range want {
		gotSum, ok := got[name]
		if !ok {
			t.Errorf("%s is in the baseline but is no longer generated", name)
			continue
		}
		if gotSum != wantSum {
			t.Errorf("%s changed (baseline %s, got %s)", name, wantSum[:12], gotSum[:12])
		}
	}
	for name := range got {
		if _, ok := want[name]; !ok {
			t.Errorf("%s is newly generated but absent from the baseline", name)
		}
	}
}

// TestCodegenIsDeterministic guards the claim ARCHITECTURE.md makes about the
// generator: "Given the same model, you get the same code every time."
//
// It did not hold. Two sources of Go map-iteration order leaked into output:
// arc dedup keyed transition→place then ranged the map (so aggregate.go's
// Inputs literal and README.md's mermaid arcs shuffled), and role-hierarchy
// flattening ranged a set (so permissions.go's AllRolesFor shuffled). Without
// this property the baseline above is meaningless, so it is checked too.
func TestCodegenIsDeterministic(t *testing.T) {
	for _, app := range freezeApps {
		t.Run(app.pkg, func(t *testing.T) {
			first := regenerate(t, app.model, app.pkg)
			for i := 0; i < 5; i++ {
				next := regenerate(t, app.model, app.pkg)
				if len(next) != len(first) {
					t.Fatalf("run %d produced %d files, first run produced %d", i, len(next), len(first))
				}
				for name, want := range first {
					if string(next[name]) != string(want) {
						t.Fatalf("run %d: %s is not reproducible:\n%s",
							i, name, firstDiff(string(want), string(next[name])))
					}
				}
			}
		})
	}
}

// gazelleOwned are files codegen emits once and Gazelle then rewrites in place.
// The generator emits srcs as a `glob(...)  # keep`; `bazel run //:gazelle`
// expands it to an explicit list. Both are correct, so they are not drift.
func gazelleOwned(name string) bool {
	return name == "BUILD.bazel" || strings.HasSuffix(name, "/BUILD.bazel")
}

// notGeneratorOutput are paths under generated/<pkg>/ that codegen does not own:
// hand-written tests, frontend output, and (in one case) a committed binary.
func notGeneratorOutput(name string) bool {
	switch name {
	case "ode_blocking_test.go", "ode_draw_test.go", "ode_heatmap_test.go":
		return true // tictactoe: hand-written ODE tests
	case "texas-holdem":
		return true // a 14 MB compiled binary committed by accident
	}
	return strings.HasPrefix(name, "frontend/")
}

// TestCommittedAppsDivergeFromGenerator measures, without failing, how far the
// committed generated/ tree has drifted from what the generator now produces.
//
// It does not assert equality: the tree predates several template changes, so it
// cannot be reproduced today. It exists so the size and shape of that gap stay
// visible (run with -v) instead of being discovered the next time someone
// regenerates an app and gets a surprise diff. Closing the gap means
// regenerating and committing all 14 apps, which is a deliberate decision.
func TestCommittedAppsDivergeFromGenerator(t *testing.T) {
	if os.Getenv("TEST_SRCDIR") != "" {
		t.Skip("reads the generated/ tree from the repo; not present in the Bazel sandbox")
	}
	root := repoRoot(t)

	var drifted, missing, added int
	for _, app := range freezeApps {
		got := regenerate(t, app.model, app.pkg)
		base := filepath.Join(root, "generated", app.pkg)

		committed := map[string][]byte{}
		err := filepath.Walk(base, func(path string, info os.FileInfo, err error) error {
			if err != nil || info.IsDir() {
				return err
			}
			rel, err := filepath.Rel(base, path)
			if err != nil {
				return err
			}
			rel = filepath.ToSlash(rel)
			if notGeneratorOutput(rel) || gazelleOwned(rel) {
				return nil
			}
			b, err := os.ReadFile(path)
			if err != nil {
				return err
			}
			committed[rel] = b
			return nil
		})
		if err != nil {
			t.Fatalf("walk %s: %v", base, err)
		}

		for name, want := range committed {
			gotContent, ok := got[name]
			if !ok {
				missing++
				t.Logf("committed but no longer generated: %s/%s", app.pkg, name)
				continue
			}
			if string(gotContent) != string(want) {
				drifted++
				t.Logf("drifted: %s/%s\n%s", app.pkg, name, firstDiff(string(want), string(gotContent)))
			}
		}
		for name := range got {
			if gazelleOwned(name) {
				continue
			}
			if _, ok := committed[name]; !ok {
				added++
				t.Logf("newly generated, not committed: %s/%s", app.pkg, name)
			}
		}
	}

	t.Logf("committed generated/ vs current generator: %d files differ, %d no longer generated, %d newly generated",
		drifted, missing, added)
}

// firstDiff reports the first differing line with a little context, which is far
// more useful than dumping two multi-thousand-line files.
func firstDiff(want, got string) string {
	wantLines := strings.Split(want, "\n")
	gotLines := strings.Split(got, "\n")

	n := len(wantLines)
	if len(gotLines) < n {
		n = len(gotLines)
	}
	for i := 0; i < n; i++ {
		if wantLines[i] != gotLines[i] {
			var b strings.Builder
			start := i - 2
			if start < 0 {
				start = 0
			}
			for j := start; j < i; j++ {
				b.WriteString("      " + wantLines[j] + "\n")
			}
			b.WriteString("  -   " + wantLines[i] + "\n")
			b.WriteString("  +   " + gotLines[i] + "\n")
			return b.String()
		}
	}
	return fmt.Sprintf("  committed has %d lines, generated has %d", len(wantLines), len(gotLines))
}
