// Command submit-ttt-proof generates a TTT ZK proof from the genesis state
// and prints the cast send command for on-chain submission.
package main

import (
	"fmt"
	"log"
	"math/big"
	"os"
	"strings"

	"github.com/pflow-xyz/go-pflow/prover"
	zkode "github.com/pflow-xyz/petri-pilot/zk-ode"
)

func main() {
	keyDir := "keys/zk-ode"
	if d := os.Getenv("ZK_KEY_DIR"); d != "" {
		keyDir = d
	}

	contractAddr := os.Getenv("TTT_ZKODE_ADDRESS")
	if contractAddr == "" {
		contractAddr = "0x5B96db6164EC6d5c8F99c650B3979EF931771Dd8"
	}

	rpcURL := os.Getenv("BASE_SEPOLIA_RPC_URL")
	if rpcURL == "" {
		rpcURL = "https://sepolia.base.org"
	}

	log.Printf("Key directory: %s", keyDir)
	log.Printf("Contract: %s", contractAddr)

	p := prover.NewProverWithKeyDir(keyDir)

	log.Println("Loading TTT circuit...")
	cc, err := p.LoadOrCompile("ttt_step", &zkode.TTTStepCircuit{})
	if err != nil {
		log.Fatalf("Failed to load circuit: %v", err)
	}
	log.Printf("Circuit ready: %d constraints", cc.Constraints)

	// Build genesis state (empty board, X's turn)
	state := zkode.NewTTTODEState(zkode.TTTDefaultInitialMarking())
	log.Printf("Genesis root: 0x%s", state.Root.Text(16))

	// Generate proof for one step from genesis
	h := zkode.FixFromFloat(0.01)
	log.Println("Generating proof (this takes ~20 seconds)...")
	result, _, witness, err := zkode.ProveTTTStep(p, state, h)
	if err != nil {
		log.Fatalf("Proof generation failed: %v", err)
	}
	log.Printf("Proof generated: %d public inputs", len(result.PublicInputs))

	// Find optimal transition (highest rate)
	bestT := 0
	bestRate := witness.ActualRates[0]
	for t := 1; t < zkode.TTTNumTransitions; t++ {
		if witness.ActualRates[t].Cmp(bestRate) > 0 {
			bestT = t
			bestRate = witness.ActualRates[t]
		}
	}
	log.Printf("Optimal transition: %d (rate: %.4f)", bestT, zkode.FixToFloat(bestRate))

	// Format proof as [p0,p1,p2,p3,p4,p5,p6,p7]
	var proofParts []string
	for _, v := range result.RawProof {
		proofParts = append(proofParts, v.Text(10))
	}
	proofStr := "[" + strings.Join(proofParts, ",") + "]"

	// Format public inputs as [i0,i1,...,i36]
	var inputParts []string
	for _, hex := range result.PublicInputs {
		v := new(big.Int)
		clean := strings.TrimPrefix(hex, "0x")
		v.SetString(clean, 16)
		inputParts = append(inputParts, v.Text(10))
	}
	inputsStr := "[" + strings.Join(inputParts, ",") + "]"

	fmt.Println()
	fmt.Println("=== Cast Send Command ===")
	fmt.Println()
	fmt.Printf("cast send %s \\\n", contractAddr)
	fmt.Printf("  \"submitStep(uint256[8],uint256[],uint256)\" \\\n")
	fmt.Printf("  \"%s\" \\\n", proofStr)
	fmt.Printf("  \"%s\" \\\n", inputsStr)
	fmt.Printf("  %d \\\n", bestT)
	fmt.Printf("  --rpc-url %s \\\n", rpcURL)
	fmt.Println("  --private-key $DEPLOYER_PRIVATE_KEY")
	fmt.Println()

	// Also write a script file for convenience
	scriptFile := "submit-ttt-proof.sh"
	script := fmt.Sprintf(`#!/bin/bash
# Submit first TTT proof on-chain
# Generated by submit-ttt-proof tool

set -e

cast send %s \
  "submitStep(uint256[8],uint256[],uint256)" \
  "%s" \
  "%s" \
  %d \
  --rpc-url %s \
  --private-key $DEPLOYER_PRIVATE_KEY
`, contractAddr, proofStr, inputsStr, bestT, rpcURL)

	if err := os.WriteFile(scriptFile, []byte(script), 0755); err != nil {
		log.Printf("Warning: could not write script file: %v", err)
	} else {
		fmt.Printf("Script saved to %s\n", scriptFile)
	}
}
