load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "shop",
    srcs = [
        "app.go",
        "bundle.go",
        "flatmodel.go",
    ],
    importpath = "github.com/pflow-xyz/petri-pilot/examples/shop",
    visibility = ["//visibility:public"],
    deps = [
        "//examples/shop/inventory",
        "//examples/shop/order",
        "@com_github_pflow_xyz_go_pflow//eventsource",
        "@com_github_pflow_xyz_go_pflow//metamodel",
    ],
)

go_test(
    name = "shop_test",
    srcs = ["app_test.go"],
    embed = [":shop"],
    deps = [
        "//examples/shop/inventory",
        "//examples/shop/order",
        "@com_github_pflow_xyz_go_pflow//eventsource",
    ],
)
