// Code generated by petri-pilot (bundle mode). DO NOT EDIT.

// Package shop is the composition root of the shop
// application: every data object is its own Petri net (see the entity
// subpackages), joined by the links recorded in the flattened model this
// package embeds.
//
// Cross-entity commands are listed in Commands: transitions the composition
// gave a firing rule no single entity can evaluate, either because an
// EventLink fused them across entities or because a GuardLink gave them a
// precondition over another entity's places. Firing one goes through App, and
// only through App — the entity packages refuse them.
package shop

// Entity names the subpackage generated for one subnet.
type Entity struct {
	SubnetID string
	Package  string
}

// Entities lists the application's data objects, one subpackage each.
var Entities = []Entity{
	{SubnetID: "inventory", Package: "inventory"},
	{SubnetID: "order", Package: "order"},
}

// CommandMember is one entity's participation in a cross-entity command.
type CommandMember struct {
	SubnetID        string
	Package         string
	LocalTransition string
	EventID         string
}

// CommandRead is one place a command's condition reads, and the entity that
// owns it. A read is not a member: the command consults it and fences it, but
// appends nothing to it.
type CommandRead struct {
	SubnetID    string
	Package     string
	LocalPlace  string
	FlatPlaceID string
}

// Command describes one cross-entity command: the transition in the flattened
// model, why the composition took it over, the entity whose API owns the
// route, the event each member appends to its own log, and the places its
// condition reads.
type Command struct {
	FlatTransition string
	Kind           string // "fused", "guarded", or "fused+guarded"
	Initiator      string
	// Condition is the cross-entity precondition app.go evaluates: the
	// flattened expression guard conjoined with a marking test for every
	// read-only arc reaching into a non-member entity.
	Condition string
	Members   []CommandMember
	Reads     []CommandRead
}

// Commands lists every cross-entity command in the bundle.
var Commands = []Command{
	{
		FlatTransition: "order_reserves_stock",
		Kind:           "fused",
		Initiator:      "order",
		Members: []CommandMember{
			{SubnetID: "inventory", Package: "inventory", LocalTransition: "reserve_stock", EventID: "inventory.reserve_stock"},
			{SubnetID: "order", Package: "order", LocalTransition: "place_order", EventID: "order.place_order"},
		},
	},
}
