// Code generated by petri-pilot (bundle mode). DO NOT EDIT.

package shop

import (
	"encoding/json"
	"sync"

	"github.com/pflow-xyz/go-pflow/metamodel"
)

// flatModelJSON is the flattened composition of every entity net — places
// and transitions after link fusion, with fused transitions carrying one
// Emits entry per member entity.
//
// It is DOCUMENTATION, not the runtime rule. Nothing loads it to decide
// whether something may fire. Enablement lives in two places and only two:
// each entity's aggregate for the local part of a firing rule, and app.go's
// generated command methods for the cross-entity part, where the guards below
// were compiled into the code that evaluates them.
//
// Saying otherwise (as this comment used to) hid a real gap for a while: the
// guards were here, so they looked enforced, and no code read them.
const flatModelJSON = "{\"name\":\"shop\",\"description\":\"Two-entity composition: placing an order reserves stock in the same atomic step.\",\"places\":[{\"id\":\"inventory/available\",\"initial\":1,\"kind\":\"token\"},{\"id\":\"inventory/reserved\",\"initial\":0,\"kind\":\"token\"},{\"id\":\"order/draft\",\"initial\":1,\"kind\":\"token\"},{\"id\":\"order/placed\",\"initial\":0,\"kind\":\"token\"},{\"id\":\"order/shipped\",\"initial\":0,\"kind\":\"token\"}],\"transitions\":[{\"id\":\"order_reserves_stock\",\"description\":\"fires with: inventory/reserve_stock, order/place_order\",\"event\":\"order.place_order\",\"emits\":[\"inventory.reserve_stock\",\"order.place_order\"]},{\"id\":\"inventory/release\",\"event\":\"inventory.release\"},{\"id\":\"order/ship\",\"event\":\"order.ship\"}],\"arcs\":[{\"from\":\"inventory/available\",\"to\":\"order_reserves_stock\",\"weight\":1},{\"from\":\"order_reserves_stock\",\"to\":\"inventory/reserved\",\"weight\":1},{\"from\":\"inventory/reserved\",\"to\":\"inventory/release\",\"weight\":1},{\"from\":\"inventory/release\",\"to\":\"inventory/available\",\"weight\":1},{\"from\":\"order/draft\",\"to\":\"order_reserves_stock\",\"weight\":1},{\"from\":\"order_reserves_stock\",\"to\":\"order/placed\",\"weight\":1},{\"from\":\"order/placed\",\"to\":\"order/ship\",\"weight\":1},{\"from\":\"order/ship\",\"to\":\"order/shipped\",\"weight\":1}]}"

var (
	flatModelOnce sync.Once
	flatModel     *metamodel.Model
)

// FlatModel returns the parsed flattened model.
func FlatModel() *metamodel.Model {
	flatModelOnce.Do(func() {
		var m metamodel.Model
		if err := json.Unmarshal([]byte(flatModelJSON), &m); err != nil {
			// The JSON is generated from a marshaled model; failure to
			// re-parse is a generator bug, not a runtime condition.
			panic("flatmodel: " + err.Error())
		}
		flatModel = &m
	})
	return flatModel
}
