// Code generated by petri-pilot. DO NOT EDIT.

package graph

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/pflow-xyz/go-pflow/eventsource"
)

// Resolver is the root resolver for GraphQL queries and mutations.
type Resolver struct {
	App interface {
		Create(ctx context.Context) (string, error)
		Load(ctx context.Context, id string) (Aggregate, error)
		GetState(ctx context.Context, id string) (Aggregate, error)
		Execute(ctx context.Context, id, transition string, data map[string]any) (Aggregate, error)
		HealthCheck(ctx context.Context) error
		GetStore() eventsource.Store
	}
}

// Aggregate interface for type safety
type Aggregate interface {
	ID() string
	Version() int
	State() any
	Places() map[string]int
	EnabledTransitions() []string
}

// NewResolver creates a new GraphQL resolver.
func NewResolver(app interface {
	Create(ctx context.Context) (string, error)
	Load(ctx context.Context, id string) (Aggregate, error)
	GetState(ctx context.Context, id string) (Aggregate, error)
	Execute(ctx context.Context, id, transition string, data map[string]any) (Aggregate, error)
	HealthCheck(ctx context.Context) error
	GetStore() eventsource.Store
}) *Resolver {
	return &Resolver{App: app}
}

// Query resolvers

// LoanApproval returns the aggregate state by ID.
func (r *Resolver) LoanApproval(ctx context.Context, id string) (*AggregateState, error) {
	agg, err := r.App.GetState(ctx, id)
	if err != nil {
		return nil, err
	}
	return aggregateToState(agg), nil
}

// LoanApprovalList returns a paginated list of aggregates.
func (r *Resolver) LoanApprovalList(ctx context.Context, place *string, page *int, perPage *int) (*AggregateList, error) {
	// Default pagination
	p := 1
	pp := 50
	if page != nil {
		p = *page
	}
	if perPage != nil {
		pp = *perPage
	}

	placeFilter := ""
	if place != nil {
		placeFilter = *place
	}
	// Admin features not enabled - return empty list
	_ = placeFilter
	return &AggregateList{
		Items:   []*AggregateState{},
		Total:   0,
		Page:    p,
		PerPage: pp,
	}, nil
}

// Events returns the event history for an aggregate.
func (r *Resolver) Events(ctx context.Context, aggregateID string, from *int) ([]*Event, error) {
	store := r.App.GetStore()
	fromVersion := 0
	if from != nil {
		fromVersion = *from
	}

	events, err := store.Read(ctx, aggregateID, fromVersion)
	if err != nil {
		return nil, err
	}

	result := make([]*Event, len(events))
	for i, evt := range events {
		data, _ := json.Marshal(evt.Data)
		result[i] = &Event{
			ID:        fmt.Sprintf("%s-%d", evt.StreamID, evt.Version),
			StreamID:  evt.StreamID,
			Type:      evt.Type,
			Version:   evt.Version,
			Timestamp: evt.Timestamp,
			Data:      string(data),
		}
	}

	return result, nil
}

// StateAtVersion returns the aggregate state at a specific version.
func (r *Resolver) StateAtVersion(ctx context.Context, aggregateID string, version int) (*AggregateState, error) {
	// This is a simplified implementation - would need aggregate rebuild logic
	agg, err := r.App.GetState(ctx, aggregateID)
	if err != nil {
		return nil, err
	}

	// TODO: Implement proper version replay
	state := aggregateToState(agg)
	state.Version = version
	return state, nil
}

// Mutation resolvers

// CreateLoanapproval creates a new aggregate instance.
func (r *Resolver) CreateLoanapproval(ctx context.Context) (*AggregateState, error) {
	id, err := r.App.Create(ctx)
	if err != nil {
		return nil, err
	}

	agg, err := r.App.Load(ctx, id)
	if err != nil {
		return nil, err
	}

	return aggregateToState(agg), nil
}

// StartReviews executes the start_reviews transition.
func (r *Resolver) StartReviews(ctx context.Context, input StartReviewsInput) (*TransitionResult, error) {
	data := make(map[string]any)

	agg, err := r.App.Execute(ctx, input.AggregateID, "start_reviews", data)
	if err != nil {
		errMsg := err.Error()
		return &TransitionResult{
			Success: false,
			Error:   &errMsg,
		}, nil
	}

	places := agg.Places()
	enabled := agg.EnabledTransitions()
	id := agg.ID()
	version := agg.Version()

	return &TransitionResult{
		Success:            true,
		AggregateID:        &id,
		Version:            &version,
		State:              placesToModel(places),
		EnabledTransitions: enabled,
	}, nil
}

// ApproveCredit executes the approve_credit transition.
func (r *Resolver) ApproveCredit(ctx context.Context, input ApproveCreditInput) (*TransitionResult, error) {
	data := make(map[string]any)

	agg, err := r.App.Execute(ctx, input.AggregateID, "approve_credit", data)
	if err != nil {
		errMsg := err.Error()
		return &TransitionResult{
			Success: false,
			Error:   &errMsg,
		}, nil
	}

	places := agg.Places()
	enabled := agg.EnabledTransitions()
	id := agg.ID()
	version := agg.Version()

	return &TransitionResult{
		Success:            true,
		AggregateID:        &id,
		Version:            &version,
		State:              placesToModel(places),
		EnabledTransitions: enabled,
	}, nil
}

// RejectCredit executes the reject_credit transition.
func (r *Resolver) RejectCredit(ctx context.Context, input RejectCreditInput) (*TransitionResult, error) {
	data := make(map[string]any)

	agg, err := r.App.Execute(ctx, input.AggregateID, "reject_credit", data)
	if err != nil {
		errMsg := err.Error()
		return &TransitionResult{
			Success: false,
			Error:   &errMsg,
		}, nil
	}

	places := agg.Places()
	enabled := agg.EnabledTransitions()
	id := agg.ID()
	version := agg.Version()

	return &TransitionResult{
		Success:            true,
		AggregateID:        &id,
		Version:            &version,
		State:              placesToModel(places),
		EnabledTransitions: enabled,
	}, nil
}

// ApproveEmployment executes the approve_employment transition.
func (r *Resolver) ApproveEmployment(ctx context.Context, input ApproveEmploymentInput) (*TransitionResult, error) {
	data := make(map[string]any)

	agg, err := r.App.Execute(ctx, input.AggregateID, "approve_employment", data)
	if err != nil {
		errMsg := err.Error()
		return &TransitionResult{
			Success: false,
			Error:   &errMsg,
		}, nil
	}

	places := agg.Places()
	enabled := agg.EnabledTransitions()
	id := agg.ID()
	version := agg.Version()

	return &TransitionResult{
		Success:            true,
		AggregateID:        &id,
		Version:            &version,
		State:              placesToModel(places),
		EnabledTransitions: enabled,
	}, nil
}

// RejectEmployment executes the reject_employment transition.
func (r *Resolver) RejectEmployment(ctx context.Context, input RejectEmploymentInput) (*TransitionResult, error) {
	data := make(map[string]any)

	agg, err := r.App.Execute(ctx, input.AggregateID, "reject_employment", data)
	if err != nil {
		errMsg := err.Error()
		return &TransitionResult{
			Success: false,
			Error:   &errMsg,
		}, nil
	}

	places := agg.Places()
	enabled := agg.EnabledTransitions()
	id := agg.ID()
	version := agg.Version()

	return &TransitionResult{
		Success:            true,
		AggregateID:        &id,
		Version:            &version,
		State:              placesToModel(places),
		EnabledTransitions: enabled,
	}, nil
}

// MergeReviews executes the merge_reviews transition.
func (r *Resolver) MergeReviews(ctx context.Context, input MergeReviewsInput) (*TransitionResult, error) {
	data := make(map[string]any)

	agg, err := r.App.Execute(ctx, input.AggregateID, "merge_reviews", data)
	if err != nil {
		errMsg := err.Error()
		return &TransitionResult{
			Success: false,
			Error:   &errMsg,
		}, nil
	}

	places := agg.Places()
	enabled := agg.EnabledTransitions()
	id := agg.ID()
	version := agg.Version()

	return &TransitionResult{
		Success:            true,
		AggregateID:        &id,
		Version:            &version,
		State:              placesToModel(places),
		EnabledTransitions: enabled,
	}, nil
}

// BeginUnderwriting executes the begin_underwriting transition.
func (r *Resolver) BeginUnderwriting(ctx context.Context, input BeginUnderwritingInput) (*TransitionResult, error) {
	data := make(map[string]any)

	agg, err := r.App.Execute(ctx, input.AggregateID, "begin_underwriting", data)
	if err != nil {
		errMsg := err.Error()
		return &TransitionResult{
			Success: false,
			Error:   &errMsg,
		}, nil
	}

	places := agg.Places()
	enabled := agg.EnabledTransitions()
	id := agg.ID()
	version := agg.Version()

	return &TransitionResult{
		Success:            true,
		AggregateID:        &id,
		Version:            &version,
		State:              placesToModel(places),
		EnabledTransitions: enabled,
	}, nil
}

// ApproveLoan executes the approve_loan transition.
func (r *Resolver) ApproveLoan(ctx context.Context, input ApproveLoanInput) (*TransitionResult, error) {
	data := make(map[string]any)

	agg, err := r.App.Execute(ctx, input.AggregateID, "approve_loan", data)
	if err != nil {
		errMsg := err.Error()
		return &TransitionResult{
			Success: false,
			Error:   &errMsg,
		}, nil
	}

	places := agg.Places()
	enabled := agg.EnabledTransitions()
	id := agg.ID()
	version := agg.Version()

	return &TransitionResult{
		Success:            true,
		AggregateID:        &id,
		Version:            &version,
		State:              placesToModel(places),
		EnabledTransitions: enabled,
	}, nil
}

// RejectLoan executes the reject_loan transition.
func (r *Resolver) RejectLoan(ctx context.Context, input RejectLoanInput) (*TransitionResult, error) {
	data := make(map[string]any)

	agg, err := r.App.Execute(ctx, input.AggregateID, "reject_loan", data)
	if err != nil {
		errMsg := err.Error()
		return &TransitionResult{
			Success: false,
			Error:   &errMsg,
		}, nil
	}

	places := agg.Places()
	enabled := agg.EnabledTransitions()
	id := agg.ID()
	version := agg.Version()

	return &TransitionResult{
		Success:            true,
		AggregateID:        &id,
		Version:            &version,
		State:              placesToModel(places),
		EnabledTransitions: enabled,
	}, nil
}

// RejectOnCredit executes the reject_on_credit transition.
func (r *Resolver) RejectOnCredit(ctx context.Context, input RejectOnCreditInput) (*TransitionResult, error) {
	data := make(map[string]any)

	agg, err := r.App.Execute(ctx, input.AggregateID, "reject_on_credit", data)
	if err != nil {
		errMsg := err.Error()
		return &TransitionResult{
			Success: false,
			Error:   &errMsg,
		}, nil
	}

	places := agg.Places()
	enabled := agg.EnabledTransitions()
	id := agg.ID()
	version := agg.Version()

	return &TransitionResult{
		Success:            true,
		AggregateID:        &id,
		Version:            &version,
		State:              placesToModel(places),
		EnabledTransitions: enabled,
	}, nil
}

// RejectOnEmployment executes the reject_on_employment transition.
func (r *Resolver) RejectOnEmployment(ctx context.Context, input RejectOnEmploymentInput) (*TransitionResult, error) {
	data := make(map[string]any)

	agg, err := r.App.Execute(ctx, input.AggregateID, "reject_on_employment", data)
	if err != nil {
		errMsg := err.Error()
		return &TransitionResult{
			Success: false,
			Error:   &errMsg,
		}, nil
	}

	places := agg.Places()
	enabled := agg.EnabledTransitions()
	id := agg.ID()
	version := agg.Version()

	return &TransitionResult{
		Success:            true,
		AggregateID:        &id,
		Version:            &version,
		State:              placesToModel(places),
		EnabledTransitions: enabled,
	}, nil
}

// Helper functions

func aggregateToState(agg Aggregate) *AggregateState {
	places := agg.Places()
	return &AggregateState{
		ID:                 agg.ID(),
		Version:            agg.Version(),
		State:              stateToModel(agg.State()),
		Places:             placesToModel(places),
		EnabledTransitions: agg.EnabledTransitions(),
	}
}

func stateToModel(state any) *State {
	s := &State{}
	// Convert struct to map via JSON roundtrip for uniform field access
	m := stateToMap(state)
	if v, ok := m["submitted"]; ok {
		s.Submitted = v
	}
	if v, ok := m["credit_review"]; ok {
		s.CreditReview = v
	}
	if v, ok := m["employment_review"]; ok {
		s.EmploymentReview = v
	}
	if v, ok := m["credit_passed"]; ok {
		s.CreditPassed = v
	}
	if v, ok := m["credit_failed"]; ok {
		s.CreditFailed = v
	}
	if v, ok := m["employment_passed"]; ok {
		s.EmploymentPassed = v
	}
	if v, ok := m["employment_failed"]; ok {
		s.EmploymentFailed = v
	}
	if v, ok := m["ready_for_decision"]; ok {
		s.ReadyForDecision = v
	}
	if v, ok := m["under_review"]; ok {
		s.UnderReview = v
	}
	if v, ok := m["approved"]; ok {
		s.Approved = v
	}
	if v, ok := m["rejected"]; ok {
		s.Rejected = v
	}
	return s
}

func stateToMap(state any) map[string]any {
	// Try direct map assertion first
	if m, ok := state.(map[string]any); ok {
		return m
	}
	// Fall back to JSON roundtrip for struct types
	b, err := json.Marshal(state)
	if err != nil {
		return nil
	}
	var m map[string]any
	if err := json.Unmarshal(b, &m); err != nil {
		return nil
	}
	return m
}

func placesToModel(places map[string]int) *Places {
	p := &Places{}
	if v, ok := places["submitted"]; ok {
		p.Submitted = v
	}
	if v, ok := places["credit_review"]; ok {
		p.CreditReview = v
	}
	if v, ok := places["employment_review"]; ok {
		p.EmploymentReview = v
	}
	if v, ok := places["credit_passed"]; ok {
		p.CreditPassed = v
	}
	if v, ok := places["credit_failed"]; ok {
		p.CreditFailed = v
	}
	if v, ok := places["employment_passed"]; ok {
		p.EmploymentPassed = v
	}
	if v, ok := places["employment_failed"]; ok {
		p.EmploymentFailed = v
	}
	if v, ok := places["ready_for_decision"]; ok {
		p.ReadyForDecision = v
	}
	if v, ok := places["under_review"]; ok {
		p.UnderReview = v
	}
	if v, ok := places["approved"]; ok {
		p.Approved = v
	}
	if v, ok := places["rejected"]; ok {
		p.Rejected = v
	}
	return p
}

// GraphQL model types

type AggregateState struct {
	ID                 string   `json:"id"`
	Version            int      `json:"version"`
	State              *State   `json:"state"`
	Places             *Places  `json:"places"`
	EnabledTransitions []string `json:"enabledTransitions"`
}

type State struct {
	Submitted        any `json:"submitted"`
	CreditReview     any `json:"creditReview"`
	EmploymentReview any `json:"employmentReview"`
	CreditPassed     any `json:"creditPassed"`
	CreditFailed     any `json:"creditFailed"`
	EmploymentPassed any `json:"employmentPassed"`
	EmploymentFailed any `json:"employmentFailed"`
	ReadyForDecision any `json:"readyForDecision"`
	UnderReview      any `json:"underReview"`
	Approved         any `json:"approved"`
	Rejected         any `json:"rejected"`
}

type Places struct {
	Submitted        int `json:"submitted"`
	CreditReview     int `json:"creditReview"`
	EmploymentReview int `json:"employmentReview"`
	CreditPassed     int `json:"creditPassed"`
	CreditFailed     int `json:"creditFailed"`
	EmploymentPassed int `json:"employmentPassed"`
	EmploymentFailed int `json:"employmentFailed"`
	ReadyForDecision int `json:"readyForDecision"`
	UnderReview      int `json:"underReview"`
	Approved         int `json:"approved"`
	Rejected         int `json:"rejected"`
}

type TransitionResult struct {
	Success            bool     `json:"success"`
	AggregateID        *string  `json:"aggregateId"`
	Version            *int     `json:"version"`
	State              *Places  `json:"state"`
	EnabledTransitions []string `json:"enabledTransitions"`
	Error              *string  `json:"error"`
}

type AggregateList struct {
	Items   []*AggregateState `json:"items"`
	Total   int               `json:"total"`
	Page    int               `json:"page"`
	PerPage int               `json:"perPage"`
}

type Event struct {
	ID        string `json:"id"`
	StreamID  string `json:"streamId"`
	Type      string `json:"type"`
	Version   int    `json:"version"`
	Timestamp any    `json:"timestamp"`
	Data      string `json:"data"`
}

// Input types

type StartReviewsInput struct {
	AggregateID string
}

type ApproveCreditInput struct {
	AggregateID string
}

type RejectCreditInput struct {
	AggregateID string
}

type ApproveEmploymentInput struct {
	AggregateID string
}

type RejectEmploymentInput struct {
	AggregateID string
}

type MergeReviewsInput struct {
	AggregateID string
}

type BeginUnderwritingInput struct {
	AggregateID string
}

type ApproveLoanInput struct {
	AggregateID string
}

type RejectLoanInput struct {
	AggregateID string
}

type RejectOnCreditInput struct {
	AggregateID string
}

type RejectOnEmploymentInput struct {
	AggregateID string
}
