// Code generated by petri-pilot. DO NOT EDIT.

package inventory

import (
	"time"
)

// InventoryReserveStockEvent is emitted when the reserve_stock transition fires.
type InventoryReserveStockEvent struct {
	AggregateId string    `json:"aggregate_id"`
	Timestamp   time.Time `json:"timestamp"`
}

// EventType returns the event type identifier.
func (e InventoryReserveStockEvent) EventType() string {
	return "inventory.reserve_stock"
}

// InventoryReleaseEvent is emitted when the release transition fires.
type InventoryReleaseEvent struct {
	AggregateId string    `json:"aggregate_id"`
	Timestamp   time.Time `json:"timestamp"`
}

// EventType returns the event type identifier.
func (e InventoryReleaseEvent) EventType() string {
	return "inventory.release"
}
