// Code generated by petri-pilot. DO NOT EDIT.

package inventory

// Place constants
const (
	PlaceAvailable = "available"
	PlaceReserved  = "reserved"
)

// Transition constants
const (
	TransitionReserveStock = "reserve_stock"
	TransitionRelease      = "release"
)

// Event type constants
const (
	EventTypeReserveStock = "inventory.reserve_stock"
	EventTypeRelease      = "inventory.release"
)

// InitialPlaces returns the initial token distribution for new aggregates.
func InitialPlaces() map[string]int {
	return map[string]int{
		PlaceAvailable: 1,
	}
}

// AllPlaces returns all place IDs in the workflow.
func AllPlaces() []string {
	return []string{
		PlaceAvailable,
		PlaceReserved,
	}
}

// AllTransitions returns all transition IDs in the workflow.
func AllTransitions() []string {
	return []string{
		TransitionReserveStock,
		TransitionRelease,
	}
}
