load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "export-ttt-verifier_lib",
    srcs = ["main.go"],
    importpath = "github.com/pflow-xyz/petri-pilot/zk-ode/cmd/export-ttt-verifier",
    visibility = ["//visibility:private"],
    deps = [
        "//zk-ode",
        "@com_github_pflow_xyz_go_pflow//prover",
    ],
)

go_binary(
    name = "export-ttt-verifier",
    embed = [":export-ttt-verifier_lib"],
    visibility = ["//visibility:public"],
)
