load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "zk-erc20",
    srcs = [
        "petri_circuits.go",
        "petri_state.go",
        "petri_token.go",
        "service.go",
    ],
    importpath = "github.com/pflow-xyz/petri-pilot/zk-erc20",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_consensys_gnark//frontend",
        "@com_github_consensys_gnark//std/hash/mimc",
        "@com_github_consensys_gnark_crypto//ecc/bn254/fr",
        "@com_github_consensys_gnark_crypto//ecc/bn254/fr/mimc",
        "@com_github_pflow_xyz_go_pflow//prover",
    ],
)

go_test(
    name = "zk-erc20_test",
    srcs = ["petri_circuits_test.go"],
    embed = [":zk-erc20"],
    deps = [
        "@com_github_consensys_gnark//frontend",
        "@com_github_consensys_gnark//frontend/cs/r1cs",
        "@com_github_consensys_gnark//test",
        "@com_github_consensys_gnark_crypto//ecc",
    ],
)
