load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "zk-verifier-provenance_lib",
    srcs = ["main.go"],
    importpath = "github.com/pflow-xyz/petri-pilot/cmd/zk-verifier-provenance",
    visibility = ["//visibility:private"],
    deps = [
        "//zk-ode",
        "@com_github_consensys_gnark//frontend",
        "@com_github_consensys_gnark//frontend/cs/r1cs",
        "@com_github_consensys_gnark//logger",
        "@com_github_consensys_gnark_crypto//ecc",
    ],
)

go_binary(
    name = "zk-verifier-provenance",
    embed = [":zk-verifier-provenance_lib"],
    visibility = ["//visibility:public"],
)
