// Code generated by petri-pilot. DO NOT EDIT.

package marchmadness2026

import (
	"encoding/json"
	"net/http"

	"github.com/pflow-xyz/petri-pilot/pkg/serve"
)

// ServiceName is the registered name for this service.
const ServiceName = "march-madness-2026"

func init() {
	serve.Register(ServiceName, NewService)
}

// Service implements serve.Service for the march-madness-2026 analysis.
type Service struct{}

// NewService creates a new march-madness-2026 service instance.
func NewService() (serve.Service, error) {
	return &Service{}, nil
}

// Name returns the service name.
func (s *Service) Name() string {
	return ServiceName
}

// BuildHandler returns the HTTP handler for this service.
func (s *Service) BuildHandler() http.Handler {
	mux := http.NewServeMux()
	mux.HandleFunc("/api/march-madness-2026/teams", s.handleTeams)
	mux.HandleFunc("/api/march-madness-2026/run", s.handleRun)
	return mux
}

// Close cleans up any resources used by the service.
func (s *Service) Close() error {
	return nil
}

func (s *Service) handleTeams(w http.ResponseWriter, r *http.Request) {
	teams := DefaultTeams()
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(teams)
}

func (s *Service) handleRun(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "text/plain")
	w.Write([]byte("Run the analysis with: go run ./generated/marchmadness2026/cmd/...\n"))
}

// DefaultTeams returns the 2026 Selection Sunday team data.
func DefaultTeams() []TeamStats {
	return []TeamStats{
		{"Duke", 1, 95, 88, 97, 92, 90},
		{"Arizona", 1, 93, 85, 96, 90, 88},
		{"Michigan", 1, 82, 92, 95, 85, 91},
		{"Florida", 1, 88, 83, 90, 95, 85},
		{"Houston", 2, 80, 95, 92, 93, 82},
		{"UConn", 2, 86, 84, 91, 78, 88},
		{"Iowa State", 2, 79, 91, 90, 80, 86},
		{"Purdue", 2, 90, 78, 88, 93, 84},
		{"Illinois", 3, 84, 82, 87, 92, 80},
		{"Gonzaga", 3, 88, 75, 91, 82, 72},
		{"Michigan St", 3, 78, 80, 86, 83, 85},
		{"Virginia", 3, 72, 90, 91, 82, 84},
		{"St John's", 5, 82, 79, 92, 95, 78},
		{"Kansas", 4, 85, 83, 82, 75, 80},
		{"Alabama", 4, 91, 72, 82, 88, 76},
		{"Nebraska", 4, 77, 81, 90, 80, 78},
	}
}
