-- Migration: 001_init_vetclinic
-- Generated by petri-pilot. DO NOT EDIT.
--
-- Event store schema for vet-clinic workflow

-- Events table: append-only event log
CREATE TABLE IF NOT EXISTS events (
    id TEXT PRIMARY KEY,
    stream_id TEXT NOT NULL,
    type TEXT NOT NULL,
    version INTEGER NOT NULL,
    data TEXT NOT NULL,  -- JSON
    metadata TEXT,       -- JSON, optional
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(stream_id, version)
);

-- Indexes for common query patterns
CREATE INDEX IF NOT EXISTS idx_events_stream_id ON events(stream_id);
CREATE INDEX IF NOT EXISTS idx_events_stream_version ON events(stream_id, version);
CREATE INDEX IF NOT EXISTS idx_events_type ON events(type);
CREATE INDEX IF NOT EXISTS idx_events_timestamp ON events(timestamp);

-- Snapshots table: periodic aggregate state snapshots for faster replay
CREATE TABLE IF NOT EXISTS snapshots (
    stream_id TEXT PRIMARY KEY,
    version INTEGER NOT NULL,
    state TEXT NOT NULL,  -- JSON
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Projection: vet-clinic aggregate state
-- Denormalized view for fast reads
CREATE TABLE IF NOT EXISTS "vetclinic_state" (
    id TEXT PRIMARY KEY,
    version INTEGER NOT NULL DEFAULT 0,
    "dvm_avail" INTEGER DEFAULT 0,
    "rvt_avail" INTEGER DEFAULT 0,
    "receptionist_avail" INTEGER DEFAULT 0,
    "exam_room_free" INTEGER DEFAULT 0,
    "surgery_free" INTEGER DEFAULT 0,
    "dental_free" INTEGER DEFAULT 0,
    "radiology_free" INTEGER DEFAULT 0,
    "treatment_free" INTEGER DEFAULT 0,
    "recovery_free" INTEGER DEFAULT 0,
    "lab_free" INTEGER DEFAULT 0,
    "surgery_day" INTEGER DEFAULT 0,
    "arrival" INTEGER DEFAULT 0,
    "wait_exam" INTEGER DEFAULT 0,
    "wait_tech" INTEGER DEFAULT 0,
    "wait_surgery" INTEGER DEFAULT 0,
    "wait_dental" INTEGER DEFAULT 0,
    "wait_diag" INTEGER DEFAULT 0,
    "wait_emergency" INTEGER DEFAULT 0,
    "wait_lab" INTEGER DEFAULT 0,
    "wait_checkout" INTEGER DEFAULT 0,
    "in_wellness" INTEGER DEFAULT 0,
    "in_sick" INTEGER DEFAULT 0,
    "in_vaccine" INTEGER DEFAULT 0,
    "in_nail_trim" INTEGER DEFAULT 0,
    "in_weight" INTEGER DEFAULT 0,
    "in_suture" INTEGER DEFAULT 0,
    "in_spay" INTEGER DEFAULT 0,
    "in_neuter" INTEGER DEFAULT 0,
    "in_dental" INTEGER DEFAULT 0,
    "in_xray" INTEGER DEFAULT 0,
    "in_bloodwork" INTEGER DEFAULT 0,
    "in_lab" INTEGER DEFAULT 0,
    "in_emergency" INTEGER DEFAULT 0,
    "checking_out" INTEGER DEFAULT 0,
    "in_recovery" INTEGER DEFAULT 0,
    "discharged" INTEGER DEFAULT 0,
    "walked_out" INTEGER DEFAULT 0,
    "diverted" INTEGER DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS "idx_vetclinic_state_updated" ON "vetclinic_state"(updated_at);

-- Place tokens tracking (Petri net state)
CREATE TABLE IF NOT EXISTS "vetclinic_places" (
    aggregate_id TEXT NOT NULL,
    place_id TEXT NOT NULL,
    tokens INTEGER NOT NULL DEFAULT 0,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (aggregate_id, place_id)
);

-- Event type constants for reference:
-- PatientArrivesed
-- EmergencyArrivesed
-- TriageToExamed
-- TriageToTeched
-- TriageToSurgeryed
-- TriageToDentaled
-- TriageToDiaged
-- StartWellnessed
-- FinishWellnessed
-- StartSicked
-- FinishSicked
-- StartVaccineed
-- FinishVaccineed
-- StartNailTrimed
-- FinishNailTrimed
-- StartWeighted
-- FinishWeighted
-- StartSutureed
-- FinishSutureed
-- StartSpayed
-- FinishSpayed
-- StartNeutered
-- FinishNeutered
-- StartDentaled
-- FinishDentaled
-- StartXrayed
-- FinishXrayed
-- StartBloodworked
-- FinishBloodworked
-- StartLabed
-- FinishLabed
-- StartEmergencyed
-- FinishEmergencyed
-- StartCheckouted
-- FinishCheckouted
-- FinishRecoveryed
-- AbandonExamed
-- AbandonTeched
-- AbandonDiaged
-- AbandonSurgeryed
-- AbandonDentaled
-- DivertEmergencyed

-- Place constants for reference:
-- dvm_avail: Available veterinarians
-- rvt_avail: Available vet techs
-- receptionist_avail: Receptionists for checkout
-- exam_room_free: Free exam rooms
-- surgery_free: Surgery suite available
-- dental_free: Dental suite available
-- radiology_free: X-ray/ultrasound room
-- treatment_free: Treatment area stations
-- recovery_free: Recovery kennels
-- lab_free: Lab equipment
-- surgery_day: Surgery gate (1 = procedures run today)
-- arrival: Patients at triage
-- wait_exam: Waiting for exam
-- wait_tech: Waiting for tech service
-- wait_surgery: Waiting for surgery
-- wait_dental: Waiting for dental
-- wait_diag: Waiting for diagnostics
-- wait_emergency: Emergency awaiting stabilization
-- wait_lab: Sample awaiting lab processing
-- wait_checkout: Waiting at the front desk
-- in_wellness: In wellness exam
-- in_sick: In sick visit
-- in_vaccine: Getting vaccinated
-- in_nail_trim: Getting nail trim
-- in_weight: Weight check
-- in_suture: Suture removal
-- in_spay: In spay surgery
-- in_neuter: In neuter surgery
-- in_dental: In dental cleaning
-- in_xray: Getting x-ray
-- in_bloodwork: Blood draw
-- in_lab: Lab test in progress
-- in_emergency: Emergency stabilization in progress
-- checking_out: Being checked out
-- in_recovery: Post-op recovery (kennel held)
-- discharged: Discharged patients
-- walked_out: Left without being seen
-- diverted: Emergencies sent to another hospital

-- Transition constants for reference:
-- patient_arrives: Scheduled/walk-in patient arrives
-- emergency_arrives: Emergency walk-in (rate 0 via simulation.solver.rates — a transition-level 0 would read as unset and default to 1)
-- triage_to_exam: Route to exam queue
-- triage_to_tech: Route to tech services
-- triage_to_surgery: Route to surgery queue
-- triage_to_dental: Route to dental queue
-- triage_to_diag: Route to diagnostics
-- start_wellness: Free DVM+RVT+room pick up a wellness exam
-- finish_wellness: Wellness exam (~20 min)
-- start_sick: Free DVM+RVT+room pick up a sick visit
-- finish_sick: Sick visit (~30 min)
-- start_vaccine: Free DVM+RVT+room pick up a vaccination
-- finish_vaccine: Vaccination (~15 min)
-- start_nail_trim: Free RVT+station pick up a nail trim
-- finish_nail_trim: Nail trim (~15 min)
-- start_weight: Free RVT+station pick up a weight check
-- finish_weight: Weight check (~10 min)
-- start_suture: Free RVT+room pick up a suture removal
-- finish_suture: Suture removal (~15 min)
-- start_spay: DVM+2 RVT+suite begin a spay (surgery day only)
-- finish_spay: Spay (~60 min); needs a free recovery kennel
-- start_neuter: DVM+2 RVT+suite begin a neuter (surgery day only)
-- finish_neuter: Neuter (~45 min); needs a free recovery kennel
-- start_dental: DVM+RVT+suite begin a dental (surgery day only)
-- finish_dental: Dental cleaning (~90 min); needs a free recovery kennel
-- start_xray: Free RVT+radiology pick up an x-ray
-- finish_xray: X-ray (~30 min)
-- start_bloodwork: Free RVT+station pick up a blood draw
-- finish_bloodwork: Blood draw (~15 min); sample goes to the lab
-- start_lab: Lab picks up a waiting sample
-- finish_lab: Lab processing (~30 min)
-- start_emergency: DVM+RVT+station stabilize an emergency
-- finish_emergency: Stabilization (~45 min); needs a recovery kennel
-- start_checkout: Receptionist picks up the next checkout
-- finish_checkout: Checkout (~10 min)
-- finish_recovery: Recovery (~60 min); kennel freed
-- abandon_exam: Exam client gives up (~30 min patience)
-- abandon_tech: Tech client gives up (~30 min patience)
-- abandon_diag: Diagnostics client gives up (~30 min patience)
-- abandon_surgery: Surgery client reschedules (~2 h patience)
-- abandon_dental: Dental client reschedules (~2 h patience)
-- divert_emergency: Emergency diverted if unseen (~15 min tolerance)
