// Code generated by petri-pilot. DO NOT EDIT.

package galtonboard

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/google/uuid"
	"github.com/pflow-xyz/go-pflow/eventsource"
)

// State holds the aggregate state for galton-board.
type State struct {
	Top  int `json:"top"`
	R10  int `json:"r1_0"`
	R11  int `json:"r1_1"`
	R20  int `json:"r2_0"`
	R21  int `json:"r2_1"`
	R22  int `json:"r2_2"`
	R30  int `json:"r3_0"`
	R31  int `json:"r3_1"`
	R32  int `json:"r3_2"`
	R33  int `json:"r3_3"`
	R40  int `json:"r4_0"`
	R41  int `json:"r4_1"`
	R42  int `json:"r4_2"`
	R43  int `json:"r4_3"`
	R44  int `json:"r4_4"`
	R50  int `json:"r5_0"`
	R51  int `json:"r5_1"`
	R52  int `json:"r5_2"`
	R53  int `json:"r5_3"`
	R54  int `json:"r5_4"`
	R55  int `json:"r5_5"`
	R60  int `json:"r6_0"`
	R61  int `json:"r6_1"`
	R62  int `json:"r6_2"`
	R63  int `json:"r6_3"`
	R64  int `json:"r6_4"`
	R65  int `json:"r6_5"`
	R66  int `json:"r6_6"`
	R70  int `json:"r7_0"`
	R71  int `json:"r7_1"`
	R72  int `json:"r7_2"`
	R73  int `json:"r7_3"`
	R74  int `json:"r7_4"`
	R75  int `json:"r7_5"`
	R76  int `json:"r7_6"`
	R77  int `json:"r7_7"`
	Bin0 int `json:"bin_0"`
	Bin1 int `json:"bin_1"`
	Bin2 int `json:"bin_2"`
	Bin3 int `json:"bin_3"`
	Bin4 int `json:"bin_4"`
	Bin5 int `json:"bin_5"`
	Bin6 int `json:"bin_6"`
	Bin7 int `json:"bin_7"`
	Bin8 int `json:"bin_8"`
}

// NewState creates a new State with initialized collections.
func NewState() State {
	return State{}
}

// Aggregate wraps a StateMachine with the galton-board state.
type Aggregate struct {
	sm *eventsource.StateMachine[State]
}

// NewAggregate creates a new aggregate with initial state.
func NewAggregate(id string) *Aggregate {
	if id == "" {
		id = uuid.New().String()
	}
	sm := eventsource.NewStateMachine(id, NewState(), InitialPlaces())

	// Register transitions with their input/output places
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP00l,
		EventType: EventTypeP00l,
		Inputs: map[string]int{
			PlaceTop: 1,
		},
		Outputs: map[string]int{
			PlaceR10: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP00r,
		EventType: EventTypeP00r,
		Inputs: map[string]int{
			PlaceTop: 1,
		},
		Outputs: map[string]int{
			PlaceR11: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP10l,
		EventType: EventTypeP10l,
		Inputs: map[string]int{
			PlaceR10: 1,
		},
		Outputs: map[string]int{
			PlaceR20: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP10r,
		EventType: EventTypeP10r,
		Inputs: map[string]int{
			PlaceR10: 1,
		},
		Outputs: map[string]int{
			PlaceR21: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP11l,
		EventType: EventTypeP11l,
		Inputs: map[string]int{
			PlaceR11: 1,
		},
		Outputs: map[string]int{
			PlaceR21: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP11r,
		EventType: EventTypeP11r,
		Inputs: map[string]int{
			PlaceR11: 1,
		},
		Outputs: map[string]int{
			PlaceR22: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP20l,
		EventType: EventTypeP20l,
		Inputs: map[string]int{
			PlaceR20: 1,
		},
		Outputs: map[string]int{
			PlaceR30: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP20r,
		EventType: EventTypeP20r,
		Inputs: map[string]int{
			PlaceR20: 1,
		},
		Outputs: map[string]int{
			PlaceR31: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP21l,
		EventType: EventTypeP21l,
		Inputs: map[string]int{
			PlaceR21: 1,
		},
		Outputs: map[string]int{
			PlaceR31: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP21r,
		EventType: EventTypeP21r,
		Inputs: map[string]int{
			PlaceR21: 1,
		},
		Outputs: map[string]int{
			PlaceR32: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP22l,
		EventType: EventTypeP22l,
		Inputs: map[string]int{
			PlaceR22: 1,
		},
		Outputs: map[string]int{
			PlaceR32: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP22r,
		EventType: EventTypeP22r,
		Inputs: map[string]int{
			PlaceR22: 1,
		},
		Outputs: map[string]int{
			PlaceR33: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP30l,
		EventType: EventTypeP30l,
		Inputs: map[string]int{
			PlaceR30: 1,
		},
		Outputs: map[string]int{
			PlaceR40: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP30r,
		EventType: EventTypeP30r,
		Inputs: map[string]int{
			PlaceR30: 1,
		},
		Outputs: map[string]int{
			PlaceR41: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP31l,
		EventType: EventTypeP31l,
		Inputs: map[string]int{
			PlaceR31: 1,
		},
		Outputs: map[string]int{
			PlaceR41: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP31r,
		EventType: EventTypeP31r,
		Inputs: map[string]int{
			PlaceR31: 1,
		},
		Outputs: map[string]int{
			PlaceR42: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP32l,
		EventType: EventTypeP32l,
		Inputs: map[string]int{
			PlaceR32: 1,
		},
		Outputs: map[string]int{
			PlaceR42: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP32r,
		EventType: EventTypeP32r,
		Inputs: map[string]int{
			PlaceR32: 1,
		},
		Outputs: map[string]int{
			PlaceR43: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP33l,
		EventType: EventTypeP33l,
		Inputs: map[string]int{
			PlaceR33: 1,
		},
		Outputs: map[string]int{
			PlaceR43: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP33r,
		EventType: EventTypeP33r,
		Inputs: map[string]int{
			PlaceR33: 1,
		},
		Outputs: map[string]int{
			PlaceR44: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP40l,
		EventType: EventTypeP40l,
		Inputs: map[string]int{
			PlaceR40: 1,
		},
		Outputs: map[string]int{
			PlaceR50: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP40r,
		EventType: EventTypeP40r,
		Inputs: map[string]int{
			PlaceR40: 1,
		},
		Outputs: map[string]int{
			PlaceR51: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP41l,
		EventType: EventTypeP41l,
		Inputs: map[string]int{
			PlaceR41: 1,
		},
		Outputs: map[string]int{
			PlaceR51: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP41r,
		EventType: EventTypeP41r,
		Inputs: map[string]int{
			PlaceR41: 1,
		},
		Outputs: map[string]int{
			PlaceR52: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP42l,
		EventType: EventTypeP42l,
		Inputs: map[string]int{
			PlaceR42: 1,
		},
		Outputs: map[string]int{
			PlaceR52: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP42r,
		EventType: EventTypeP42r,
		Inputs: map[string]int{
			PlaceR42: 1,
		},
		Outputs: map[string]int{
			PlaceR53: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP43l,
		EventType: EventTypeP43l,
		Inputs: map[string]int{
			PlaceR43: 1,
		},
		Outputs: map[string]int{
			PlaceR53: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP43r,
		EventType: EventTypeP43r,
		Inputs: map[string]int{
			PlaceR43: 1,
		},
		Outputs: map[string]int{
			PlaceR54: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP44l,
		EventType: EventTypeP44l,
		Inputs: map[string]int{
			PlaceR44: 1,
		},
		Outputs: map[string]int{
			PlaceR54: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP44r,
		EventType: EventTypeP44r,
		Inputs: map[string]int{
			PlaceR44: 1,
		},
		Outputs: map[string]int{
			PlaceR55: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP50l,
		EventType: EventTypeP50l,
		Inputs: map[string]int{
			PlaceR50: 1,
		},
		Outputs: map[string]int{
			PlaceR60: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP50r,
		EventType: EventTypeP50r,
		Inputs: map[string]int{
			PlaceR50: 1,
		},
		Outputs: map[string]int{
			PlaceR61: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP51l,
		EventType: EventTypeP51l,
		Inputs: map[string]int{
			PlaceR51: 1,
		},
		Outputs: map[string]int{
			PlaceR61: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP51r,
		EventType: EventTypeP51r,
		Inputs: map[string]int{
			PlaceR51: 1,
		},
		Outputs: map[string]int{
			PlaceR62: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP52l,
		EventType: EventTypeP52l,
		Inputs: map[string]int{
			PlaceR52: 1,
		},
		Outputs: map[string]int{
			PlaceR62: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP52r,
		EventType: EventTypeP52r,
		Inputs: map[string]int{
			PlaceR52: 1,
		},
		Outputs: map[string]int{
			PlaceR63: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP53l,
		EventType: EventTypeP53l,
		Inputs: map[string]int{
			PlaceR53: 1,
		},
		Outputs: map[string]int{
			PlaceR63: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP53r,
		EventType: EventTypeP53r,
		Inputs: map[string]int{
			PlaceR53: 1,
		},
		Outputs: map[string]int{
			PlaceR64: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP54l,
		EventType: EventTypeP54l,
		Inputs: map[string]int{
			PlaceR54: 1,
		},
		Outputs: map[string]int{
			PlaceR64: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP54r,
		EventType: EventTypeP54r,
		Inputs: map[string]int{
			PlaceR54: 1,
		},
		Outputs: map[string]int{
			PlaceR65: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP55l,
		EventType: EventTypeP55l,
		Inputs: map[string]int{
			PlaceR55: 1,
		},
		Outputs: map[string]int{
			PlaceR65: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP55r,
		EventType: EventTypeP55r,
		Inputs: map[string]int{
			PlaceR55: 1,
		},
		Outputs: map[string]int{
			PlaceR66: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP60l,
		EventType: EventTypeP60l,
		Inputs: map[string]int{
			PlaceR60: 1,
		},
		Outputs: map[string]int{
			PlaceR70: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP60r,
		EventType: EventTypeP60r,
		Inputs: map[string]int{
			PlaceR60: 1,
		},
		Outputs: map[string]int{
			PlaceR71: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP61l,
		EventType: EventTypeP61l,
		Inputs: map[string]int{
			PlaceR61: 1,
		},
		Outputs: map[string]int{
			PlaceR71: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP61r,
		EventType: EventTypeP61r,
		Inputs: map[string]int{
			PlaceR61: 1,
		},
		Outputs: map[string]int{
			PlaceR72: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP62l,
		EventType: EventTypeP62l,
		Inputs: map[string]int{
			PlaceR62: 1,
		},
		Outputs: map[string]int{
			PlaceR72: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP62r,
		EventType: EventTypeP62r,
		Inputs: map[string]int{
			PlaceR62: 1,
		},
		Outputs: map[string]int{
			PlaceR73: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP63l,
		EventType: EventTypeP63l,
		Inputs: map[string]int{
			PlaceR63: 1,
		},
		Outputs: map[string]int{
			PlaceR73: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP63r,
		EventType: EventTypeP63r,
		Inputs: map[string]int{
			PlaceR63: 1,
		},
		Outputs: map[string]int{
			PlaceR74: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP64l,
		EventType: EventTypeP64l,
		Inputs: map[string]int{
			PlaceR64: 1,
		},
		Outputs: map[string]int{
			PlaceR74: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP64r,
		EventType: EventTypeP64r,
		Inputs: map[string]int{
			PlaceR64: 1,
		},
		Outputs: map[string]int{
			PlaceR75: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP65l,
		EventType: EventTypeP65l,
		Inputs: map[string]int{
			PlaceR65: 1,
		},
		Outputs: map[string]int{
			PlaceR75: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP65r,
		EventType: EventTypeP65r,
		Inputs: map[string]int{
			PlaceR65: 1,
		},
		Outputs: map[string]int{
			PlaceR76: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP66l,
		EventType: EventTypeP66l,
		Inputs: map[string]int{
			PlaceR66: 1,
		},
		Outputs: map[string]int{
			PlaceR76: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP66r,
		EventType: EventTypeP66r,
		Inputs: map[string]int{
			PlaceR66: 1,
		},
		Outputs: map[string]int{
			PlaceR77: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP70l,
		EventType: EventTypeP70l,
		Inputs: map[string]int{
			PlaceR70: 1,
		},
		Outputs: map[string]int{
			PlaceBin0: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP70r,
		EventType: EventTypeP70r,
		Inputs: map[string]int{
			PlaceR70: 1,
		},
		Outputs: map[string]int{
			PlaceBin1: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP71l,
		EventType: EventTypeP71l,
		Inputs: map[string]int{
			PlaceR71: 1,
		},
		Outputs: map[string]int{
			PlaceBin1: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP71r,
		EventType: EventTypeP71r,
		Inputs: map[string]int{
			PlaceR71: 1,
		},
		Outputs: map[string]int{
			PlaceBin2: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP72l,
		EventType: EventTypeP72l,
		Inputs: map[string]int{
			PlaceR72: 1,
		},
		Outputs: map[string]int{
			PlaceBin2: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP72r,
		EventType: EventTypeP72r,
		Inputs: map[string]int{
			PlaceR72: 1,
		},
		Outputs: map[string]int{
			PlaceBin3: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP73l,
		EventType: EventTypeP73l,
		Inputs: map[string]int{
			PlaceR73: 1,
		},
		Outputs: map[string]int{
			PlaceBin3: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP73r,
		EventType: EventTypeP73r,
		Inputs: map[string]int{
			PlaceR73: 1,
		},
		Outputs: map[string]int{
			PlaceBin4: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP74l,
		EventType: EventTypeP74l,
		Inputs: map[string]int{
			PlaceR74: 1,
		},
		Outputs: map[string]int{
			PlaceBin4: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP74r,
		EventType: EventTypeP74r,
		Inputs: map[string]int{
			PlaceR74: 1,
		},
		Outputs: map[string]int{
			PlaceBin5: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP75l,
		EventType: EventTypeP75l,
		Inputs: map[string]int{
			PlaceR75: 1,
		},
		Outputs: map[string]int{
			PlaceBin5: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP75r,
		EventType: EventTypeP75r,
		Inputs: map[string]int{
			PlaceR75: 1,
		},
		Outputs: map[string]int{
			PlaceBin6: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP76l,
		EventType: EventTypeP76l,
		Inputs: map[string]int{
			PlaceR76: 1,
		},
		Outputs: map[string]int{
			PlaceBin6: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP76r,
		EventType: EventTypeP76r,
		Inputs: map[string]int{
			PlaceR76: 1,
		},
		Outputs: map[string]int{
			PlaceBin7: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP77l,
		EventType: EventTypeP77l,
		Inputs: map[string]int{
			PlaceR77: 1,
		},
		Outputs: map[string]int{
			PlaceBin7: 1,
		},
	})
	sm.AddTransition(eventsource.Transition{
		ID:        TransitionP77r,
		EventType: EventTypeP77r,
		Inputs: map[string]int{
			PlaceR77: 1,
		},
		Outputs: map[string]int{
			PlaceBin8: 1,
		},
	})

	// Register event handlers for state updates
	sm.RegisterHandler(EventTypeP00l, func(state *State, event *eventsource.Event) error {
		return applyP00l(state, event)
	})
	sm.RegisterHandler(EventTypeP00r, func(state *State, event *eventsource.Event) error {
		return applyP00r(state, event)
	})
	sm.RegisterHandler(EventTypeP10l, func(state *State, event *eventsource.Event) error {
		return applyP10l(state, event)
	})
	sm.RegisterHandler(EventTypeP10r, func(state *State, event *eventsource.Event) error {
		return applyP10r(state, event)
	})
	sm.RegisterHandler(EventTypeP11l, func(state *State, event *eventsource.Event) error {
		return applyP11l(state, event)
	})
	sm.RegisterHandler(EventTypeP11r, func(state *State, event *eventsource.Event) error {
		return applyP11r(state, event)
	})
	sm.RegisterHandler(EventTypeP20l, func(state *State, event *eventsource.Event) error {
		return applyP20l(state, event)
	})
	sm.RegisterHandler(EventTypeP20r, func(state *State, event *eventsource.Event) error {
		return applyP20r(state, event)
	})
	sm.RegisterHandler(EventTypeP21l, func(state *State, event *eventsource.Event) error {
		return applyP21l(state, event)
	})
	sm.RegisterHandler(EventTypeP21r, func(state *State, event *eventsource.Event) error {
		return applyP21r(state, event)
	})
	sm.RegisterHandler(EventTypeP22l, func(state *State, event *eventsource.Event) error {
		return applyP22l(state, event)
	})
	sm.RegisterHandler(EventTypeP22r, func(state *State, event *eventsource.Event) error {
		return applyP22r(state, event)
	})
	sm.RegisterHandler(EventTypeP30l, func(state *State, event *eventsource.Event) error {
		return applyP30l(state, event)
	})
	sm.RegisterHandler(EventTypeP30r, func(state *State, event *eventsource.Event) error {
		return applyP30r(state, event)
	})
	sm.RegisterHandler(EventTypeP31l, func(state *State, event *eventsource.Event) error {
		return applyP31l(state, event)
	})
	sm.RegisterHandler(EventTypeP31r, func(state *State, event *eventsource.Event) error {
		return applyP31r(state, event)
	})
	sm.RegisterHandler(EventTypeP32l, func(state *State, event *eventsource.Event) error {
		return applyP32l(state, event)
	})
	sm.RegisterHandler(EventTypeP32r, func(state *State, event *eventsource.Event) error {
		return applyP32r(state, event)
	})
	sm.RegisterHandler(EventTypeP33l, func(state *State, event *eventsource.Event) error {
		return applyP33l(state, event)
	})
	sm.RegisterHandler(EventTypeP33r, func(state *State, event *eventsource.Event) error {
		return applyP33r(state, event)
	})
	sm.RegisterHandler(EventTypeP40l, func(state *State, event *eventsource.Event) error {
		return applyP40l(state, event)
	})
	sm.RegisterHandler(EventTypeP40r, func(state *State, event *eventsource.Event) error {
		return applyP40r(state, event)
	})
	sm.RegisterHandler(EventTypeP41l, func(state *State, event *eventsource.Event) error {
		return applyP41l(state, event)
	})
	sm.RegisterHandler(EventTypeP41r, func(state *State, event *eventsource.Event) error {
		return applyP41r(state, event)
	})
	sm.RegisterHandler(EventTypeP42l, func(state *State, event *eventsource.Event) error {
		return applyP42l(state, event)
	})
	sm.RegisterHandler(EventTypeP42r, func(state *State, event *eventsource.Event) error {
		return applyP42r(state, event)
	})
	sm.RegisterHandler(EventTypeP43l, func(state *State, event *eventsource.Event) error {
		return applyP43l(state, event)
	})
	sm.RegisterHandler(EventTypeP43r, func(state *State, event *eventsource.Event) error {
		return applyP43r(state, event)
	})
	sm.RegisterHandler(EventTypeP44l, func(state *State, event *eventsource.Event) error {
		return applyP44l(state, event)
	})
	sm.RegisterHandler(EventTypeP44r, func(state *State, event *eventsource.Event) error {
		return applyP44r(state, event)
	})
	sm.RegisterHandler(EventTypeP50l, func(state *State, event *eventsource.Event) error {
		return applyP50l(state, event)
	})
	sm.RegisterHandler(EventTypeP50r, func(state *State, event *eventsource.Event) error {
		return applyP50r(state, event)
	})
	sm.RegisterHandler(EventTypeP51l, func(state *State, event *eventsource.Event) error {
		return applyP51l(state, event)
	})
	sm.RegisterHandler(EventTypeP51r, func(state *State, event *eventsource.Event) error {
		return applyP51r(state, event)
	})
	sm.RegisterHandler(EventTypeP52l, func(state *State, event *eventsource.Event) error {
		return applyP52l(state, event)
	})
	sm.RegisterHandler(EventTypeP52r, func(state *State, event *eventsource.Event) error {
		return applyP52r(state, event)
	})
	sm.RegisterHandler(EventTypeP53l, func(state *State, event *eventsource.Event) error {
		return applyP53l(state, event)
	})
	sm.RegisterHandler(EventTypeP53r, func(state *State, event *eventsource.Event) error {
		return applyP53r(state, event)
	})
	sm.RegisterHandler(EventTypeP54l, func(state *State, event *eventsource.Event) error {
		return applyP54l(state, event)
	})
	sm.RegisterHandler(EventTypeP54r, func(state *State, event *eventsource.Event) error {
		return applyP54r(state, event)
	})
	sm.RegisterHandler(EventTypeP55l, func(state *State, event *eventsource.Event) error {
		return applyP55l(state, event)
	})
	sm.RegisterHandler(EventTypeP55r, func(state *State, event *eventsource.Event) error {
		return applyP55r(state, event)
	})
	sm.RegisterHandler(EventTypeP60l, func(state *State, event *eventsource.Event) error {
		return applyP60l(state, event)
	})
	sm.RegisterHandler(EventTypeP60r, func(state *State, event *eventsource.Event) error {
		return applyP60r(state, event)
	})
	sm.RegisterHandler(EventTypeP61l, func(state *State, event *eventsource.Event) error {
		return applyP61l(state, event)
	})
	sm.RegisterHandler(EventTypeP61r, func(state *State, event *eventsource.Event) error {
		return applyP61r(state, event)
	})
	sm.RegisterHandler(EventTypeP62l, func(state *State, event *eventsource.Event) error {
		return applyP62l(state, event)
	})
	sm.RegisterHandler(EventTypeP62r, func(state *State, event *eventsource.Event) error {
		return applyP62r(state, event)
	})
	sm.RegisterHandler(EventTypeP63l, func(state *State, event *eventsource.Event) error {
		return applyP63l(state, event)
	})
	sm.RegisterHandler(EventTypeP63r, func(state *State, event *eventsource.Event) error {
		return applyP63r(state, event)
	})
	sm.RegisterHandler(EventTypeP64l, func(state *State, event *eventsource.Event) error {
		return applyP64l(state, event)
	})
	sm.RegisterHandler(EventTypeP64r, func(state *State, event *eventsource.Event) error {
		return applyP64r(state, event)
	})
	sm.RegisterHandler(EventTypeP65l, func(state *State, event *eventsource.Event) error {
		return applyP65l(state, event)
	})
	sm.RegisterHandler(EventTypeP65r, func(state *State, event *eventsource.Event) error {
		return applyP65r(state, event)
	})
	sm.RegisterHandler(EventTypeP66l, func(state *State, event *eventsource.Event) error {
		return applyP66l(state, event)
	})
	sm.RegisterHandler(EventTypeP66r, func(state *State, event *eventsource.Event) error {
		return applyP66r(state, event)
	})
	sm.RegisterHandler(EventTypeP70l, func(state *State, event *eventsource.Event) error {
		return applyP70l(state, event)
	})
	sm.RegisterHandler(EventTypeP70r, func(state *State, event *eventsource.Event) error {
		return applyP70r(state, event)
	})
	sm.RegisterHandler(EventTypeP71l, func(state *State, event *eventsource.Event) error {
		return applyP71l(state, event)
	})
	sm.RegisterHandler(EventTypeP71r, func(state *State, event *eventsource.Event) error {
		return applyP71r(state, event)
	})
	sm.RegisterHandler(EventTypeP72l, func(state *State, event *eventsource.Event) error {
		return applyP72l(state, event)
	})
	sm.RegisterHandler(EventTypeP72r, func(state *State, event *eventsource.Event) error {
		return applyP72r(state, event)
	})
	sm.RegisterHandler(EventTypeP73l, func(state *State, event *eventsource.Event) error {
		return applyP73l(state, event)
	})
	sm.RegisterHandler(EventTypeP73r, func(state *State, event *eventsource.Event) error {
		return applyP73r(state, event)
	})
	sm.RegisterHandler(EventTypeP74l, func(state *State, event *eventsource.Event) error {
		return applyP74l(state, event)
	})
	sm.RegisterHandler(EventTypeP74r, func(state *State, event *eventsource.Event) error {
		return applyP74r(state, event)
	})
	sm.RegisterHandler(EventTypeP75l, func(state *State, event *eventsource.Event) error {
		return applyP75l(state, event)
	})
	sm.RegisterHandler(EventTypeP75r, func(state *State, event *eventsource.Event) error {
		return applyP75r(state, event)
	})
	sm.RegisterHandler(EventTypeP76l, func(state *State, event *eventsource.Event) error {
		return applyP76l(state, event)
	})
	sm.RegisterHandler(EventTypeP76r, func(state *State, event *eventsource.Event) error {
		return applyP76r(state, event)
	})
	sm.RegisterHandler(EventTypeP77l, func(state *State, event *eventsource.Event) error {
		return applyP77l(state, event)
	})
	sm.RegisterHandler(EventTypeP77r, func(state *State, event *eventsource.Event) error {
		return applyP77r(state, event)
	})
	return &Aggregate{sm: sm}
}

// ID returns the aggregate identifier.
func (a *Aggregate) ID() string {
	return a.sm.ID()
}

// Version returns the current event version.
func (a *Aggregate) Version() int {
	return a.sm.Version()
}

// State returns the current state.
func (a *Aggregate) State() any {
	return a.sm.State()
}

// Places returns current token distribution.
func (a *Aggregate) Places() map[string]int {
	places := make(map[string]int)
	for _, p := range AllPlaces() {
		places[p] = a.sm.Tokens(p)
	}
	return places
}

// EnabledTransitions returns transitions that can fire.
func (a *Aggregate) EnabledTransitions() []string {
	return a.sm.EnabledTransitions()
}

// CanFire checks if a transition can fire.
func (a *Aggregate) CanFire(transitionID string) bool {
	return a.sm.CanFire(transitionID)
}

// Fire executes a transition and returns the resulting event.
func (a *Aggregate) Fire(transitionID string, data any) (*eventsource.Event, error) {
	return a.sm.Fire(transitionID, data)
}

// Apply applies an event to update the aggregate state.
func (a *Aggregate) Apply(event *eventsource.Event) error {
	// Update state machine (this calls the registered handlers)
	return a.sm.Apply(event)
}

// Event application functions

func applyP00l(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP00r(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP10l(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP10r(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP11l(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP11r(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP20l(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP20r(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP21l(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP21r(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP22l(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP22r(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP30l(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP30r(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP31l(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP31r(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP32l(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP32r(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP33l(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP33r(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP40l(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP40r(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP41l(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP41r(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP42l(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP42r(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP43l(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP43r(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP44l(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP44r(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP50l(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP50r(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP51l(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP51r(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP52l(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP52r(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP53l(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP53r(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP54l(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP54r(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP55l(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP55r(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP60l(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP60r(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP61l(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP61r(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP62l(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP62r(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP63l(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP63r(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP64l(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP64r(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP65l(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP65r(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP66l(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP66r(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP70l(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP70r(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP71l(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP71r(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP72l(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP72r(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP73l(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP73r(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP74l(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP74r(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP75l(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP75r(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP76l(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP76r(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP77l(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

func applyP77r(state *State, event *eventsource.Event) error {
	// No data transformations for this transition
	_ = state
	_ = event
	return nil
}

// Application wires together the aggregate and event store.
type Application struct {
	store eventsource.Store
}

// NewApplication creates a new application instance.
func NewApplication(store eventsource.Store) *Application {
	return &Application{store: store}
}

// Create creates a new aggregate and returns its ID.
func (app *Application) Create(ctx context.Context) (string, error) {
	agg := NewAggregate("")
	return agg.ID(), nil
}

// Load loads an aggregate from the event store.
func (app *Application) Load(ctx context.Context, id string) (*Aggregate, error) {
	events, err := app.store.Read(ctx, id, 0)
	if err != nil {
		return nil, fmt.Errorf("reading events: %w", err)
	}

	agg := NewAggregate(id)
	for _, event := range events {
		if err := agg.Apply(event); err != nil {
			return nil, fmt.Errorf("applying event %s: %w", event.ID, err)
		}
	}

	return agg, nil
}

// Execute fires a transition on an aggregate and persists the event.
func (app *Application) Execute(ctx context.Context, id, transitionID string, data any) (*Aggregate, error) {
	// Load current state
	agg, err := app.Load(ctx, id)
	if err != nil {
		return nil, err
	}

	// Check if transition can fire
	if !agg.CanFire(transitionID) {
		return nil, fmt.Errorf("transition %s cannot fire from current state", transitionID)
	}

	// Fire transition (this updates token counts but not version)
	event, err := agg.Fire(transitionID, data)
	if err != nil {
		return nil, fmt.Errorf("firing transition: %w", err)
	}

	// Persist event (this assigns the event version)
	// The expected version should match the current stream version (-1 for new streams)
	_, err = app.store.Append(ctx, id, agg.Version(), []*eventsource.Event{event})
	if err != nil {
		return nil, fmt.Errorf("persisting event: %w", err)
	}

	// Apply the event to update the aggregate's version
	if err := agg.Apply(event); err != nil {
		return nil, fmt.Errorf("applying event: %w", err)
	}

	return agg, nil
}

// GetState returns the current state of an aggregate.
func (app *Application) GetState(ctx context.Context, id string) (*Aggregate, error) {
	return app.Load(ctx, id)
}

// TruncateTo truncates an aggregate's event stream to a specific version.
// Events after the target version are removed. This enables "undo and redo differently" workflows.
func (app *Application) TruncateTo(ctx context.Context, id string, targetVersion int) (*Aggregate, error) {
	// Read all events
	events, err := app.store.Read(ctx, id, 0)
	if err != nil {
		return nil, fmt.Errorf("reading events: %w", err)
	}

	// Validate target version
	if targetVersion < 0 || targetVersion > len(events) {
		return nil, fmt.Errorf("invalid target version %d (stream has %d events)", targetVersion, len(events))
	}

	// If already at target, just load and return
	if targetVersion == len(events) {
		return app.Load(ctx, id)
	}

	// Keep only events up to target version
	eventsToKeep := events[:targetVersion]

	// Delete the stream
	if err := app.store.DeleteStream(ctx, id); err != nil {
		return nil, fmt.Errorf("deleting stream: %w", err)
	}

	// Re-append the events we want to keep
	if len(eventsToKeep) > 0 {
		if _, err := app.store.Append(ctx, id, -1, eventsToKeep); err != nil {
			return nil, fmt.Errorf("re-appending events: %w", err)
		}
	}

	// Load and return the truncated aggregate
	return app.Load(ctx, id)
}

// HealthCheck verifies the event store is accessible.
func (app *Application) HealthCheck(ctx context.Context) error {
	// Try to read from a non-existent stream - this exercises the store connection
	_, err := app.store.Read(ctx, "__health_check__", 0)
	// Ignore "not found" errors - we just want to verify connectivity
	if err != nil && err.Error() != "stream not found" {
		return err
	}
	return nil
}

// Helper to unmarshal event data
func unmarshalEventData[T any](event *eventsource.Event) (*T, error) {
	var data T
	if err := json.Unmarshal(event.Data, &data); err != nil {
		return nil, err
	}
	return &data, nil
}
